// @ts-check
// The sidebar is generated from the docs/ folder structure (order via sidebar_position frontmatter
// and _category_.json files), so adding a page is just adding a markdown file.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
