/**
 * FLY — the spine (command API) target (SPEC-012). Emits a real `spine/fly.toml` so the generated Express
 * service can `fly deploy`. Hosts the `node` engine (the spine). When the spine is on Fly (managed) it no
 * longer runs as a local compose service, so `spine` is pruned; dependants reach it via `SPINE_URL`. The
 * spine still needs its own store/n8n reach vars set as Fly secrets — documented in the note, not baked.
 */
import type { DeployTarget } from "./registry.ts";

export const FLY: DeployTarget = {
  id: "fly",
  name: "Fly.io",
  modes: ["managed", "selfhost"],
  hosts: (ctx) => ctx.engineId === "node",
  generate: (ctx) => {
    const app = `${ctx.domainSlug || "app"}-spine`;
    const flyToml = `# Generated by @kiln/codegen (SPEC-012) — Fly.io config for the spine (command API).
app = "${app}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"

# Set reach + secrets with: fly secrets set DATABASE_URL=... N8N_BASE_URL=... API_TOKEN=...
`;
    return {
      files: { "spine/fly.toml": flyToml },
      prunesComposeService: [ctx.composeService],
      env: { SPINE_URL: `# SPINE_URL=https://${app}.fly.dev   # dependants (UI, n8n, Odoo) → deployed spine URL` },
      reach: `\`cd spine && fly deploy\` (uses \`spine/fly.toml\`); \`fly secrets set DATABASE_URL=… N8N_BASE_URL=…\`.`,
    };
  },
};
