/**
 * generateApp — project the model into a COMPLETE, RUNNABLE full-stack starter (not just scaffolding).
 * Returns a file map (path → contents): a zero-dependency Node API (entities CRUD + command endpoints
 * + in-memory store + event log + reactions) and a Vite/React admin client, both driven by the model.
 * The API runs with `node server.mjs` (no install); the client with `cd web && npm i && npm run dev`.
 *
 * This is the deterministic base — correct and runnable by construction. The LLM enhancement pass
 * (generateAppLogic) rewrites the command handler + component bodies with real domain logic on top.
 */

import { slug } from "@vbd/ir";
import { attributeSpecs, type CapabilityDoc, type DomainDoc, type ContextsDoc, type RolesDoc } from "@vbd/compiler";

export interface AppModel {
  domain: string;
  entities: { id: string; name: string; owner: string; area: string; fields: { name: string; type: string }[]; references: string[] }[];
  commands: { id: string; name: string; entity: string; emits: string[] }[];
  events: { id: string; name: string; entity: string; trigger: string }[];
  policies: { name: string; on: string; then: string }[];
  areas: { name: string; capabilities: string[] }[];
  roles: { name: string; capabilities: string[] }[];
  /** entity id → role names allowed to write it (derived from role→capability→entity ownership). */
  permissions: Record<string, string[]>;
}

/** Distil the IR into the flat, slugged shape the generated app is driven by. */
export function projectAppModel(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc, rolesDoc?: RolesDoc): AppModel {
  const areaOfCap = new Map<string, string>();
  for (const c of contexts?.contexts ?? []) for (const m of [...(c.capabilities ?? []), ...(c.shared_kernel ?? [])]) areaOfCap.set(m, c.name || c.id);
  const roles = (rolesDoc?.roles ?? []).map((r) => ({ name: r.name || r.id, capabilities: (r.capabilities ?? []) }));
  const entities = domain.aggregates.map((a) => ({
    id: slug(a.id),
    name: a.name || a.id,
    owner: a.owner,
    area: areaOfCap.get(a.owner) ?? "General",
    fields: attributeSpecs(a).map((s) => ({ name: s.name, type: s.type || "text" })),
    references: (a.references ?? []).map((r) => slug(r)),
  }));
  // A role may write an entity if it operates the capability that owns it. No roles modelled → open.
  const permissions: Record<string, string[]> = {};
  for (const e of entities) {
    const allowed = roles.filter((r) => r.capabilities.includes(e.owner)).map((r) => r.name);
    if (allowed.length) permissions[e.id] = allowed;
  }
  return {
    domain: caps.domain || "business",
    entities,
    commands: (domain.commands ?? []).map((c) => ({ id: slug(c.id), name: c.name, entity: slug(c.aggregate), emits: (c.emits ?? []).map((e) => slug(e)) })),
    events: (domain.events ?? []).map((e) => ({ id: slug(e.id), name: e.name, entity: slug(e.aggregate), trigger: e.trigger || "command" })),
    policies: (domain.policies ?? []).map((p) => ({ name: p.name, on: slug(p.on), then: slug(p.then) })),
    areas: (contexts?.contexts ?? []).map((c) => ({ name: c.name || c.id, capabilities: (c.capabilities ?? []).map((m) => slug(m)) })),
    roles,
    permissions,
  };
}

/** Standardised documentation banner (What / Why / Dependencies / Decisions) for a generated file. */
function banner(what: string, why: string, deps: string, decisions: string): string {
  return `/**\n * ${what}\n *\n * Why:          ${why}\n * Dependencies: ${deps}\n * Decisions:    ${decisions}\n *\n * Generated by VerticalBusinessDesigner from the business model. Refine freely.\n */\n`;
}

const J = (v: unknown): string => JSON.stringify(v, null, 2);

/** The command-handler module (business logic per command). Generic by default; the LLM pass swaps
 *  in richer bodies. Kept in its own file so enhancement is an isolated, low-risk file replacement. */
function handlersFile(m: AppModel, overrides: Record<string, string> = {}): string {
  const lines = [
    banner(
      "Command handlers — the business logic for each modelled command.",
      "isolates domain logic from transport, so it can evolve or be regenerated independently.",
      "none — pure functions (input, ctx) => record; ctx = { genId, all(entity), find(entity,id) }.",
      "generic pass-through by default; the AI-logic export fills in defaults, computed fields and validation.",
    ).trimEnd(),
    "export const HANDLERS = {",
  ];
  for (const c of m.commands) {
    const body = overrides[c.id]?.trim() || "(input, ctx) => ({ ...input })";
    lines.push(`  ${JSON.stringify(c.id)}: ${body}, // ${c.name} → ${c.entity}`);
  }
  lines.push("};");
  return lines.join("\n");
}

// Coerce a raw value to the field's declared type — the deterministic half of input validation.
const COERCERS: Record<string, string> = {
  number: "(v) => (v === '' || v == null ? null : Number(v))",
  money: "(v) => (v === '' || v == null ? null : Number(v))",
  boolean: "(v) => v === true || v === 'true' || v === 1",
  date: "(v) => (v ? String(v) : null)",
  text: "(v) => (v == null ? null : String(v))",
  reference: "(v) => (v == null ? null : String(v))",
};

/** The zero-dependency Node API server (runs with `node server.mjs`) — validated, access-controlled, documented. */
function serverFile(m: AppModel): string {
  const schema = Object.fromEntries(m.entities.map((e) => [e.id, e.fields]));
  return `${banner(
    `${m.domain} API — REST over the modelled entities + a command endpoint per business action.`,
    "runnable back end for the generated app; the model's automations fire here as real hand-offs.",
    "node:http only (zero npm dependencies) — runs with `node server.mjs`.",
    "in-memory store (swap for a DB); typed-field validation; role-gated writes via x-role header (scaffold — replace with real auth).",
  )}import { createServer } from 'node:http';
import { HANDLERS } from './handlers.mjs';

export const MODEL = ${J({ entities: m.entities, commands: m.commands, events: m.events, policies: m.policies })};
// Field types per entity (for validation) and write permissions per entity (from the roles layer).
const SCHEMA = ${J(schema)};
const PERMISSIONS = ${J(m.permissions)};
const COERCE = { ${Object.entries(COERCERS).map(([k, v]) => `${k}: ${v}`).join(", ")} };

// Security config — override in production.
const CORS_ORIGIN = process.env.CORS_ORIGIN || '*';        // set to your web origin in prod
const AUTH = process.env.AUTH !== 'off';                    // role checks on; set AUTH=off to disable
const PORT = process.env.PORT || 8787;

const db = Object.fromEntries(MODEL.entities.map(e => [e.id, []]));
const eventLog = [];
let seq = 1;
const genId = () => 'id_' + (seq++);

/** Validate + coerce an input object against an entity's declared fields. Unknown keys are dropped. */
function validate(entityId, input) {
  const fields = SCHEMA[entityId] || [];
  const clean = {};
  const errors = [];
  for (const f of fields) {
    if (input[f.name] === undefined) continue;
    const coerced = (COERCE[f.type] || COERCE.text)(input[f.name]);
    if ((f.type === 'number' || f.type === 'money') && input[f.name] !== '' && Number.isNaN(coerced)) errors.push(f.name + ' must be a number');
    else clean[f.name] = coerced;
  }
  return { clean, errors };
}

/** Does the caller's role permit writing this entity? Open if the entity has no modelled owner-role. */
function mayWrite(entityId, role) {
  if (!AUTH) return true;
  const allowed = PERMISSIONS[entityId];
  return !allowed || allowed.length === 0 || allowed.includes(role);
}

// Execute a modelled command: run its handler to build the record, append emitted events, and fire
// any reactions (policies) whose trigger event matches — a real cross-entity hand-off, depth-guarded.
export function runCommand(cmdId, input = {}, depth = 0) {
  const cmd = MODEL.commands.find(c => c.id === cmdId);
  if (!cmd) throw new Error('unknown command ' + cmdId);
  const { clean } = validate(cmd.entity, input);
  const ctx = { genId, all: (e) => db[e] || [], find: (e, id) => (db[e] || []).find(r => r.id === id) };
  let built = {};
  // Handlers receive ONLY validated+coerced fields (never raw input) so validation can't be bypassed.
  try { built = HANDLERS[cmdId] ? HANDLERS[cmdId](clean, ctx) : { ...clean }; } catch (e) { built = { ...clean, _handlerError: String(e && e.message || e) }; }
  const rec = { id: genId(), ...built, _command: cmdId, _at: Date.now() };
  (db[cmd.entity] ||= []).push(rec);
  const emitted = [];
  for (const evId of cmd.emits) {
    const ev = { id: genId(), type: evId, entity: cmd.entity, command: cmdId, at: Date.now() };
    eventLog.push(ev); emitted.push(evId);
    if (depth < 5) for (const p of MODEL.policies) if (p.on === evId) {
      try { runCommand(p.then, { _reactedTo: evId }, depth + 1); } catch { /* reaction target not runnable yet */ }
    }
  }
  return { record: rec, emitted };
}

const HEADERS = {
  'content-type': 'application/json',
  'access-control-allow-origin': CORS_ORIGIN,
  'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS',
  'access-control-allow-headers': 'content-type,x-role',
  'x-content-type-options': 'nosniff',           // don't let browsers MIME-sniff responses
  'referrer-policy': 'no-referrer',
};
const send = (res, code, body) => { res.writeHead(code, HEADERS); res.end(JSON.stringify(body)); };
// Cap the body size (1 MB) so a huge payload can't exhaust memory, and reject invalid JSON.
const readBody = (req) => new Promise((resolve, reject) => { let d = ''; req.on('data', c => { d += c; if (d.length > 1e6) { req.destroy(); reject(new Error('payload too large')); } }); req.on('end', () => { try { resolve(d ? JSON.parse(d) : {}); } catch { reject(new Error('invalid JSON')); } }); });

createServer(async (req, res) => {
  if (req.method === 'OPTIONS') return send(res, 204, {});
  const url = new URL(req.url, 'http://x');
  const parts = url.pathname.replace(/^\\/api\\//, '').split('/').filter(Boolean);
  const role = req.headers['x-role'] || '';
  try {
    if (parts[0] === 'meta') return send(res, 200, MODEL);
    if (parts[0] === 'events') return send(res, 200, eventLog);
    if (parts[0] === 'commands' && req.method === 'POST') {
      const cmd = MODEL.commands.find(c => c.id === parts[1]);
      if (cmd && !mayWrite(cmd.entity, role)) return send(res, 403, { error: 'role not permitted' });
      return send(res, 200, runCommand(parts[1], await readBody(req)));
    }
    const entity = parts[0];
    if (!db[entity]) return send(res, 404, { error: 'no such entity: ' + entity });
    const id = parts[1];
    if (req.method === 'GET' && !id) return send(res, 200, db[entity]);
    if (req.method === 'GET' && id) return send(res, 200, db[entity].find(r => r.id === id) || null);
    if (req.method !== 'GET' && !mayWrite(entity, role)) return send(res, 403, { error: 'role not permitted' });
    if (req.method === 'POST') { const { clean, errors } = validate(entity, await readBody(req)); if (errors.length) return send(res, 422, { errors }); const rec = { id: genId(), ...clean }; db[entity].push(rec); return send(res, 201, rec); }
    if (req.method === 'PUT' && id) { const i = db[entity].findIndex(r => r.id === id); if (i < 0) return send(res, 404, {}); const { clean, errors } = validate(entity, await readBody(req)); if (errors.length) return send(res, 422, { errors }); db[entity][i] = { ...db[entity][i], ...clean }; return send(res, 200, db[entity][i]); }
    if (req.method === 'DELETE' && id) { db[entity] = db[entity].filter(r => r.id !== id); return send(res, 200, { ok: true }); }
    send(res, 405, { error: 'method not allowed' });
  } catch (e) { send(res, 400, { error: String(e && e.message || e) }); }
}).listen(PORT, () => console.log('API on http://localhost:' + PORT + (AUTH ? ' (role checks on)' : '')));
`;
}

/** The React client (Vite). State-based nav (no router dep): a screen per entity + an events view. */
function clientFiles(m: AppModel): Record<string, string> {
  return {
    "web/package.json": J({
      name: `${slug(m.domain)}-web`,
      private: true,
      type: "module",
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
      dependencies: { react: "^18.2.0", "react-dom": "^18.2.0" },
      devDependencies: { "@vitejs/plugin-react": "^4.2.0", vite: "^5.0.0" },
    }),
    "web/vite.config.js": `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n// Proxy /api to the Node server so the client can fetch it in dev.\nexport default defineConfig({ plugins: [react()], server: { proxy: { '/api': 'http://localhost:8787' } } });\n`,
    "web/index.html": `<!doctype html>\n<html><head><meta charset="utf-8"><title>${m.domain} admin</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>\n`,
    "web/src/main.jsx": `import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { App } from './App.jsx';\nimport './styles.css';\ncreateRoot(document.getElementById('root')).render(<App />);\n`,
    "web/src/schema.js": `// The model, shared with the API. Drives every generated screen.\nexport const MODEL = ${J({ domain: m.domain, entities: m.entities, commands: m.commands, events: m.events, areas: m.areas, roles: m.roles.map((r) => r.name), permissions: m.permissions })};\n`,
    "web/src/api.js": `${banner("API client — thin fetch wrapper; carries the selected role as the x-role header.", "single place the UI talks to the server; keeps auth + JSON handling in one spot.", "none (browser fetch).", "role is a demo scaffold sent per request — replace with a real auth token.")}const j = (r) => r.json();\nlet currentRole = '';\nexport const setRole = (r) => { currentRole = r; };\nconst H = () => ({ 'content-type': 'application/json', 'x-role': currentRole });\nexport const api = {\n  list: (e) => fetch('/api/' + e, { headers: H() }).then(j),\n  create: (e, body) => fetch('/api/' + e, { method: 'POST', headers: H(), body: JSON.stringify(body) }).then(j),\n  remove: (e, id) => fetch('/api/' + e + '/' + id, { method: 'DELETE', headers: H() }).then(j),\n  command: (id, body) => fetch('/api/commands/' + id, { method: 'POST', headers: H(), body: JSON.stringify(body || {}) }).then(j),\n  events: () => fetch('/api/events').then(j),\n};\n`,
    "web/src/App.jsx": `${banner("Admin shell — sidebar of entities grouped by business area + the active screen.", "the entry point of the generated client UI.", "react; ./schema.js; ./components/*.", "state-based navigation (no router dependency) to keep the client minimal.")}import React, { useState } from 'react';\nimport { MODEL } from './schema.js';\nimport { EntityScreen } from './components/EntityScreen.jsx';\nimport { EventsScreen } from './components/EventsScreen.jsx';\nimport { setRole } from './api.js';\n\nexport function App() {\n  const [screen, setScreen] = useState(MODEL.entities[0]?.id || 'events');\n  const [role, setRoleState] = useState('');\n  const byArea = {};\n  for (const e of MODEL.entities) (byArea[e.area] ||= []).push(e);\n  return (\n    <div className="app">\n      <aside>\n        <h1>${m.domain}</h1>\n        {MODEL.roles.length > 0 && (<select className="role-select" value={role} onChange={e => { setRole(e.target.value); setRoleState(e.target.value); }}>\n          <option value="">(sign in as role…)</option>\n          {MODEL.roles.map(r => <option key={r} value={r}>{r}</option>)}\n        </select>)}\n        {Object.entries(byArea).map(([area, ents]) => (\n          <div key={area} className="area"><div className="area-name">{area}</div>\n            {ents.map(e => <button key={e.id} className={screen === e.id ? 'sel' : ''} onClick={() => setScreen(e.id)}>{e.name}</button>)}\n          </div>\n        ))}\n        <div className="area"><div className="area-name">System</div>\n          <button className={screen === 'events' ? 'sel' : ''} onClick={() => setScreen('events')}>Event log</button>\n        </div>\n      </aside>\n      <main>{screen === 'events' ? <EventsScreen /> : <EntityScreen key={screen} entity={MODEL.entities.find(e => e.id === screen)} />}</main>\n    </div>\n  );\n}\n`,
    "web/src/components/EntityScreen.jsx": `${banner("Generic entity screen — a table, a typed create form, and this entity's command buttons.", "one component renders every entity from its schema, so screens stay in sync with the model.", "react; ../schema.js; ../api.js.", "form inputs are chosen from each field's declared type; refine per entity as needed.")}import React, { useEffect, useState } from 'react';\nimport { MODEL } from '../schema.js';\nimport { api } from '../api.js';\n\nexport function EntityScreen({ entity }) {\n  const [rows, setRows] = useState([]);\n  const [form, setForm] = useState({});\n  const commands = MODEL.commands.filter(c => c.entity === entity.id);\n  const load = () => api.list(entity.id).then(setRows);\n  useEffect(() => { load(); }, [entity.id]);\n  const set = (name, val) => setForm(f => ({ ...f, [name]: val }));\n  const create = async () => { await api.create(entity.id, form); setForm({}); load(); };\n  return (\n    <div>\n      <h2>{entity.name}</h2>\n      <table><thead><tr><th>id</th>{entity.fields.map(f => <th key={f.name}>{f.name}</th>)}<th></th></tr></thead>\n        <tbody>{rows.map(r => (<tr key={r.id}><td>{r.id}</td>{entity.fields.map(f => <td key={f.name}>{String(r[f.name] ?? '')}</td>)}<td><button onClick={async () => { await api.remove(entity.id, r.id); load(); }}>✕</button></td></tr>))}</tbody>\n      </table>\n      <div className="form"><h3>New {entity.name}</h3>\n        {entity.fields.map(f => (<label key={f.name}>{f.name} <span className="muted">{f.type}</span>\n          <input type={ {number:'number',money:'number',date:'date',boolean:'checkbox'}[f.type] || 'text' } checked={f.type==='boolean'?!!form[f.name]:undefined} value={f.type==='boolean'?undefined:(form[f.name] ?? '')} onChange={e => set(f.name, f.type==='boolean'?e.target.checked:e.target.value)} />\n        </label>))}\n        <button className="primary" onClick={create}>Create</button>\n      </div>\n      {commands.length > 0 && (<div className="commands"><h3>Actions</h3>\n        {commands.map(c => <button key={c.id} onClick={async () => { await api.command(c.id, form); setForm({}); load(); }}>{c.name}</button>)}\n      </div>)}\n    </div>\n  );\n}\n`,
    "web/src/components/EventsScreen.jsx": `import React, { useEffect, useState } from 'react';\nimport { api } from '../api.js';\nexport function EventsScreen() {\n  const [events, setEvents] = useState([]);\n  useEffect(() => { const t = setInterval(() => api.events().then(setEvents), 1000); api.events().then(setEvents); return () => clearInterval(t); }, []);\n  return (<div><h2>Event log</h2><table><thead><tr><th>type</th><th>entity</th><th>from command</th></tr></thead>\n    <tbody>{events.map(e => <tr key={e.id}><td>{e.type}</td><td>{e.entity}</td><td>{e.command}</td></tr>)}</tbody></table></div>);\n}\n`,
    "web/src/styles.css": `* { box-sizing: border-box; } body { margin: 0; font: 14px system-ui, sans-serif; color: #1f2937; }\n.app { display: flex; min-height: 100vh; }\naside { width: 220px; background: #0f172a; color: #cbd5e1; padding: 16px; }\naside h1 { font-size: 16px; color: #fff; text-transform: capitalize; }\n.role-select { width: 100%; margin: 10px 0; padding: 5px; background: #1e293b; color: #cbd5e1; border: 1px solid #334155; border-radius: 5px; }\n.area-name { margin: 14px 0 4px; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #64748b; }\naside button { display: block; width: 100%; text-align: left; background: none; border: none; color: #cbd5e1; padding: 5px 8px; border-radius: 5px; cursor: pointer; }\naside button:hover, aside button.sel { background: #1e293b; color: #fff; }\nmain { flex: 1; padding: 24px; }\ntable { border-collapse: collapse; width: 100%; margin-bottom: 20px; }\nth, td { border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; }\nth { background: #f9fafb; }\n.form, .commands { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px; max-width: 480px; }\nlabel { display: block; margin-bottom: 8px; } label input { display: block; width: 100%; padding: 5px; margin-top: 2px; }\nlabel input[type=checkbox] { width: auto; }\n.muted { color: #9ca3af; font-size: 12px; }\nbutton.primary { background: #4f46e5; color: #fff; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; }\n.commands button { margin: 0 8px 8px 0; padding: 6px 12px; border: 1px solid #4f46e5; color: #4f46e5; background: #fff; border-radius: 6px; cursor: pointer; }\n`,
  };
}

export function generateApp(
  caps: CapabilityDoc,
  domain: DomainDoc,
  contexts?: ContextsDoc,
  roles?: RolesDoc,
  handlerCode?: Record<string, string>, // optional LLM-written handler bodies, keyed by command id
): Record<string, string> {
  const m = projectAppModel(caps, domain, contexts, roles);
  const files: Record<string, string> = {
    "package.json": J({
      name: `${slug(m.domain)}-app`,
      private: true,
      type: "module",
      scripts: { start: "node server.mjs", lint: "eslint . && cd web && npm run lint", format: "prettier --write ." },
      devDependencies: { eslint: "^9.0.0", prettier: "^3.2.0" },
      description: `Generated ${m.domain} app — API + admin client, derived from the business model.`,
    }),
    "server.mjs": serverFile(m),
    "handlers.mjs": handlersFile(m, handlerCode ?? {}),
    "model.json": J(m),
    "README.md": readme(m),
    "ARCHITECTURE.md": architectureDoc(m),
    ...qaConfigFiles(),
    ...clientFiles(m),
  };
  return files;
}

/** Deterministic QA baseline: lint + format + editor config shared by the repo (root + web). */
function qaConfigFiles(): Record<string, string> {
  const eslint = `// Flat ESLint config — baseline hygiene for the generated code.\nexport default [\n  { ignores: ['**/node_modules/**', 'web/dist/**'] },\n  {\n    languageOptions: { ecmaVersion: 2023, sourceType: 'module' },\n    rules: {\n      'no-unused-vars': 'warn',\n      'no-undef': 'off',\n      'prefer-const': 'warn',\n      eqeqeq: ['warn', 'smart'],\n      'no-var': 'error',\n    },\n  },\n];\n`;
  const prettier = J({ printWidth: 100, singleQuote: true, semi: true, trailingComma: "all" });
  const editorconfig = `root = true\n\n[*]\ncharset = utf-8\nindent_style = space\nindent_size = 2\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\n`;
  const gitignore = `node_modules/\nweb/dist/\n.DS_Store\n*.log\n.env\n`;
  const jsconfig = J({ compilerOptions: { target: "ES2022", module: "ESNext", moduleResolution: "Bundler", checkJs: false, jsx: "react-jsx" }, exclude: ["node_modules", "web/dist"] });
  return {
    "eslint.config.js": eslint,
    ".prettierrc": prettier,
    ".editorconfig": editorconfig,
    ".gitignore": gitignore,
    "jsconfig.json": jsconfig,
    "web/eslint.config.js": eslint,
    "web/.prettierrc": prettier,
  };
}

function architectureDoc(m: AppModel): string {
  const list = (xs: string[]) => (xs.length ? xs.map((x) => `- ${x}`).join("\n") : "- (none)");
  return `# Architecture — ${m.domain}

Generated from a VerticalBusinessDesigner model. This documents **what** each part is, **why** it exists, and the **decisions** baked in.

## Overview
A two-tier app: a zero-dependency Node API (\`server.mjs\`) over an in-memory store, and a Vite/React admin (\`web/\`). Both are driven by the same model (\`model.json\`).

## Domain model (entities)
${list(m.entities.map((e) => `**${e.name}** (\`${e.id}\`, area: ${e.area}) — fields: ${e.fields.map((f) => `${f.name}:${f.type}`).join(", ") || "none"}${e.references.length ? `; references ${e.references.join(", ")}` : ""}`))}

## Behaviour (commands → events)
${list(m.commands.map((c) => `**${c.name}** on \`${c.entity}\`${c.emits.length ? ` → emits ${c.emits.join(", ")}` : ""}`))}

## Automations (reactions)
${list(m.policies.map((p) => `on \`${p.on}\` → run \`${p.then}\``))}

## Roles & access
${m.roles.length ? list(m.roles.map((r) => `**${r.name}** — operates ${r.capabilities.join(", ") || "(none)"}`)) : "- No roles modelled — writes are open. Add roles in the designer to gate them."}
Write access is enforced in \`server.mjs\` via the \`x-role\` header against \`PERMISSIONS\` (a scaffold — replace with real authentication).

## Business areas
${list(m.areas.map((a) => `**${a.name}** — ${a.capabilities.join(", ")}`))}

## Key decisions
- **In-memory store** for zero-setup runnability — swap the \`db\` object in \`server.mjs\` for a real database (SQLite/Postgres) when persistence is needed.
- **Command endpoints** (not just CRUD) so business actions and their events/automations are first-class.
- **Typed-field validation** and **role-gated writes** are enforced server-side; the client mirrors the field types.
- **Handlers isolated** in \`handlers.mjs\` so business logic can evolve (or be regenerated) without touching transport.

## Security notes (before production)
- Set \`CORS_ORIGIN\` to your web origin (defaults to \`*\`).
- Replace the \`x-role\` scaffold with real authentication + session management.
- Move the store to a database and add persistence, migrations and backups.
`;
}

function readme(m: AppModel): string {
  return `# ${m.domain} — generated application

A runnable full-stack starter derived from the business model (${m.entities.length} entities, ${m.commands.length} commands, ${m.events.length} events, ${m.policies.length} automations).

## Run it

**API** (no install needed — zero dependencies):
\`\`\`
node server.mjs        # http://localhost:8787
\`\`\`

**Admin client:**
\`\`\`
cd web && npm install && npm run dev    # http://localhost:5173 (proxies /api to the server)
\`\`\`

## What's here
- \`server.mjs\` — REST per entity (typed-field validation, role-gated writes), a POST endpoint per command (record + events + automations), an event log. In-memory store.
- \`handlers.mjs\` — the business logic per command (isolated so it can be refined/regenerated).
- \`web/\` — a React admin: a role picker, a screen per entity (typed form + command buttons) grouped by business area, and a live event log.
- \`ARCHITECTURE.md\` — what/why/decisions + security notes. \`model.json\` — the source model.
- \`eslint.config.js\`, \`.prettierrc\`, \`.editorconfig\`, \`jsconfig.json\` — lint/format/editor baseline.

## Quality
\`\`\`
npm run format     # prettier
npm run lint       # eslint (run: npm i, then npm run lint)
\`\`\`

## Security (before production)
- Writes are gated by role via the \`x-role\` header (a **scaffold** — replace with real auth). Set \`AUTH=off\` to disable, \`CORS_ORIGIN\` to your web origin.
- Swap the in-memory store for a database.

This is a starting point to refine — the model wires the structure; the handler + screen bodies are yours (or the AI-logic export's) to flesh out.
`;
}
