/**
 * @kiln/codegen/hoppscotch — a ready-to-use Hoppscotch (open-source API tester) collection for the spine.
 *
 * We already emit OpenAPI, but a *meaningful* collection is more useful on day one: a request per command
 * with an example JSON body built from the entity's typed fields, grouped by entity, pointed at the
 * spine's real POST routes (+ /health) via a `baseUrl` env var. Import collection.json + environment.json
 * into Hoppscotch (or hoppscotch.io). Schemas: collection v12, request v17 (from hoppscotch-data).
 *
 * Pure and isomorphic — deterministic ids (slug-based), no node:* / random.
 */

import { slug } from "@kiln/ir";
import { attributeSpecs, type AttrType, type CapabilityDoc, type DomainDoc, type ContextsDoc } from "@kiln/compiler";

const CREATE_VERB = /^(create|add|register|open|new|capture|issue|request|submit|plan|record)_/;
const EXAMPLE: Record<AttrType, unknown> = { text: "example", number: 0, boolean: false, date: "2026-01-01", money: 0, reference: "" };

const jsonHeader = () => [{ key: "content-type", value: "application/json", active: true, description: "" }];
const inheritAuth = () => ({ authType: "inherit", authActive: true });

interface HoppRequest {
  v: string;
  endpoint: string;
  name: string;
  method: string;
  headers: Array<Record<string, unknown>>;
  params: unknown[];
  body: { contentType: string | null; body: string | null };
  auth: Record<string, unknown>;
  preRequestScript: string;
  testScript: string;
  requestVariables: unknown[];
  responses: Record<string, unknown>;
  _ref_id: string;
  description: string | null;
}

function req(name: string, method: string, endpoint: string, body: unknown, id: string): HoppRequest {
  return {
    v: "17",
    endpoint,
    name,
    method,
    headers: method === "POST" ? jsonHeader() : [],
    params: [],
    body: method === "POST" ? { contentType: "application/json", body: JSON.stringify(body, null, 2) } : { contentType: null, body: null },
    auth: inheritAuth(),
    preRequestScript: "",
    testScript: "",
    requestVariables: [],
    responses: {},
    _ref_id: `req_${id}`,
    description: null,
  };
}

/** Build a Hoppscotch collection (per-entity folders of command requests) + an environment. */
export function hoppscotchCollection(caps: CapabilityDoc, domain: DomainDoc, _contexts?: ContextsDoc): { collection: Record<string, unknown>; environment: Record<string, unknown> } {
  const exampleBody = (aggId: string) => {
    const a = domain.aggregates.find((x) => x.id === aggId);
    const body: Record<string, unknown> = {};
    for (const f of attributeSpecs({ attributes: a?.attributes ?? [] })) body[slug(f.name)] = f.type ? EXAMPLE[f.type] : "example";
    return body;
  };

  const folders = domain.aggregates
    .map((a) => {
      const table = slug(a.id);
      const cmds = (domain.commands ?? []).filter((c) => c.aggregate === a.id);
      if (!cmds.length) return null;
      const requests = cmds.map((c) => {
        const action = slug(c.name || c.id);
        const create = CREATE_VERB.test(`${action}_`);
        const endpoint = create ? `<<baseUrl>>/${table}s` : `<<baseUrl>>/${table}s/<<id>>/${action}`;
        return req(c.name || c.id, "POST", endpoint, exampleBody(a.id), slug(c.id));
      });
      return { v: 12, name: a.name || a.id, _ref_id: `coll_${table}`, folders: [], requests, auth: inheritAuth(), headers: [], variables: [], description: null, preRequestScript: "", testScript: "" };
    })
    .filter(Boolean);

  const collection = {
    v: 12,
    name: `${caps.domain || "Business"} API (spine)`,
    _ref_id: `coll_${slug(caps.domain || "api")}`,
    folders,
    requests: [req("Health", "GET", "<<baseUrl>>/health", null, "health")],
    auth: inheritAuth(),
    headers: [],
    variables: [],
    description: "Generated by @kiln/codegen — one request per command, bodies from the entity types.",
    preRequestScript: "",
    testScript: "",
  };

  const environment = {
    v: 1,
    name: `${caps.domain || "Business"} — local`,
    variables: [
      { key: "baseUrl", value: "http://localhost:3000", secret: false },
      { key: "id", value: "r_example", secret: false },
    ],
  };

  return { collection, environment };
}
