/**
 * @vbd/codegen — the codegen PROBE (RES-001). A deterministic projection of the model into code
 * artifacts: TypeScript types, an OpenAPI sketch, and an area→module map. This is a *compiler pass*,
 * not an LLM task — it fits "text is truth, code is a projection" (golden invariant #1) and the
 * feasibility note's "generation as one-way scaffolding" stance.
 *
 * Its real job is to answer two questions the whole product rests on:
 *   1. Does the model (capabilities + entities + areas) carry enough structure to generate anything
 *      useful?  → the artifacts below.
 *   2. What is MISSING for faithful codegen?  → the `gaps` list, which is the probe's finding and
 *      tells us what the next modelling investment must add (typed attributes, behaviour/commands).
 *
 * Pure and isomorphic (no node:*), like the other @vbd packages.
 */

import { slug } from "@vbd/ir";
import { attributeSpecs, type AttrType, type CapabilityDoc, type DomainDoc, type ContextsDoc } from "@vbd/compiler";

/** Business attribute type → TypeScript type. */
const TS_TYPE: Record<AttrType, string> = {
  text: "string",
  number: "number",
  boolean: "boolean",
  date: "string",
  money: "number",
  reference: "string",
};

/** Business attribute type → OpenAPI schema fragment. */
const OA_TYPE: Record<AttrType, Record<string, string>> = {
  text: { type: "string" },
  number: { type: "number" },
  boolean: { type: "boolean" },
  date: { type: "string", format: "date" },
  money: { type: "number", format: "decimal" },
  reference: { type: "string", format: "id" },
};

const pascal = (s: string): string =>
  slug(s)
    .split("_")
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

const plural = (s: string): string => (s.endsWith("s") ? s : `${s}s`);

export interface CodegenReport {
  types: string;
  openapi: Record<string, unknown>;
  moduleMap: string;
  /** what the model cannot yet express — the probe's finding (RES-001). */
  gaps: string[];
}

/** TypeScript interface per aggregate. Attributes are currently UNTYPED names → `unknown` (a gap). */
export function generateTypes(caps: CapabilityDoc, domain: DomainDoc): string {
  const lines: string[] = ["// Generated by @vbd/codegen — DO NOT EDIT. Source of truth is the model.", ""];
  for (const a of domain.aggregates) {
    lines.push(`export interface ${pascal(a.name || a.id)} {`);
    lines.push(`  id: string;`);
    for (const attr of attributeSpecs(a)) {
      const ts = attr.type ? TS_TYPE[attr.type] : "unknown";
      const note = attr.type ? "" : " // TODO: attribute type not modelled";
      lines.push(`  ${slug(attr.name)}: ${ts};${note}`);
    }
    for (const ref of a.references ?? []) lines.push(`  ${slug(ref)}Id: string; // reference → ${ref}`);
    lines.push(`}`, "");
  }
  return lines.join("\n");
}

/** Minimal OpenAPI 3 sketch: a CRUD resource per aggregate, tagged by its owning capability's area. */
export function generateOpenApi(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc): Record<string, unknown> {
  const areaOfCap = new Map<string, string>();
  for (const c of contexts?.contexts ?? []) for (const m of [...(c.capabilities ?? []), ...(c.shared_kernel ?? [])]) areaOfCap.set(m, c.name || c.id);

  const paths: Record<string, unknown> = {};
  const schemas: Record<string, unknown> = {};
  for (const a of domain.aggregates) {
    const T = pascal(a.name || a.id);
    const res = plural(slug(a.id));
    const tag = areaOfCap.get(a.owner) ?? a.owner ?? "ungrouped";
    const props: Record<string, unknown> = { id: { type: "string" } };
    for (const attr of attributeSpecs(a)) props[slug(attr.name)] = attr.type ? OA_TYPE[attr.type] : { description: "type not modelled" };
    schemas[T] = { type: "object", properties: props };
    const ref = { $ref: `#/components/schemas/${T}` };
    paths[`/${res}`] = {
      get: { tags: [tag], summary: `List ${T}`, responses: { "200": { description: "ok" } } },
      post: { tags: [tag], summary: `Create ${T}`, requestBody: { content: { "application/json": { schema: ref } } }, responses: { "201": { description: "created" } } },
    };
    paths[`/${res}/{id}`] = {
      get: { tags: [tag], summary: `Get ${T}`, responses: { "200": { description: "ok" } } },
      put: { tags: [tag], summary: `Update ${T}`, responses: { "200": { description: "ok" } } },
      delete: { tags: [tag], summary: `Delete ${T}`, responses: { "204": { description: "deleted" } } },
    };
  }
  return {
    openapi: "3.0.3",
    info: { title: `${caps.domain} API (scaffold)`, version: "0.0.0" },
    paths,
    components: { schemas },
  };
}

/** A text tree: business area → capabilities → the aggregates they own. Areas as module seams. */
export function generateModuleMap(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc): string {
  const aggByOwner = new Map<string, string[]>();
  for (const a of domain.aggregates) {
    const list = aggByOwner.get(a.owner) ?? [];
    list.push(a.name || a.id);
    aggByOwner.set(a.owner, list);
  }
  const nameOfCap = new Map(caps.capabilities.map((c) => [c.id, c.name || c.id]));
  const lines: string[] = [];
  const areas = contexts?.contexts ?? [{ id: "all", name: caps.domain, intent: "", capabilities: caps.capabilities.map((c) => c.id) }];
  for (const area of areas) {
    lines.push(`module ${slug(area.id)}/  # ${area.name}`);
    for (const capId of area.capabilities ?? []) {
      lines.push(`  ${slug(capId)}/  # ${nameOfCap.get(capId) ?? capId}`);
      for (const agg of aggByOwner.get(capId) ?? []) lines.push(`    ${slug(agg)}.ts`);
    }
  }
  return lines.join("\n");
}

/** Detect what the model cannot yet express — the probe's central finding (RES-001). */
export function detectGaps(caps: CapabilityDoc, domain: DomainDoc): string[] {
  const gaps: string[] = [];
  const untyped = domain.aggregates.reduce((n, a) => n + attributeSpecs(a).filter((s) => !s.type).length, 0);
  if (untyped > 0) {
    gaps.push(
      `${untyped} attributes across ${domain.aggregates.length} entities are UNTYPED → those fields emit \`unknown\`. Give them a business type (text/number/boolean/date/money/reference) for faithful schemas.`,
    );
  }
  const noAttrs = domain.aggregates.filter((a) => (a.attributes ?? []).length === 0).map((a) => a.id);
  if (noAttrs.length) gaps.push(`${noAttrs.length} entities have NO attributes (${noAttrs.join(", ")}) → empty records.`);

  const owners = new Set(domain.aggregates.map((a) => a.owner));
  const noResource = caps.capabilities.filter((c) => !owners.has(c.id)).map((c) => c.id);
  if (noResource.length) gaps.push(`${noResource.length} capabilities own no entity (${noResource.join(", ")}) → no data resource generated.`);

  // The headline gap: without the behaviour layer (SPEC-004) the API is CRUD-only.
  gaps.push(
    "Operations are CRUD-only: the model has no commands/events, so domain actions (e.g. \"Qualify Lead\", \"Issue Invoice\") and their events cannot be generated. This is exactly the SPEC-004 behaviour layer — the probe confirms it is the next codegen-relevant modelling need.",
  );
  return gaps;
}

export function generateAll(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc): CodegenReport {
  return {
    types: generateTypes(caps, domain),
    openapi: generateOpenApi(caps, domain, contexts),
    moduleMap: generateModuleMap(caps, domain, contexts),
    gaps: detectGaps(caps, domain),
  };
}
