/**
 * @vbd/codegen — the codegen PROBE (RES-001). A deterministic projection of the model into code
 * artifacts: TypeScript types, an OpenAPI sketch, and an area→module map. This is a *compiler pass*,
 * not an LLM task — it fits "text is truth, code is a projection" (golden invariant #1) and the
 * feasibility note's "generation as one-way scaffolding" stance.
 *
 * Its real job is to answer two questions the whole product rests on:
 *   1. Does the model (capabilities + entities + areas) carry enough structure to generate anything
 *      useful?  → the artifacts below.
 *   2. What is MISSING for faithful codegen?  → the `gaps` list, which is the probe's finding and
 *      tells us what the next modelling investment must add (typed attributes, behaviour/commands).
 *
 * Pure and isomorphic (no node:*), like the other @vbd packages.
 */

import { slug } from "@vbd/ir";
import { attributeSpecs, type AttrType, type CapabilityDoc, type DomainDoc, type ContextsDoc, type RolesDoc, type WorkflowsDoc, type AgentsDoc } from "@vbd/compiler";

/** Business attribute type → TypeScript type. */
const TS_TYPE: Record<AttrType, string> = {
  text: "string",
  number: "number",
  boolean: "boolean",
  date: "string",
  money: "number",
  reference: "string",
};

/** Business attribute type → OpenAPI schema fragment. */
const OA_TYPE: Record<AttrType, Record<string, string>> = {
  text: { type: "string" },
  number: { type: "number" },
  boolean: { type: "boolean" },
  date: { type: "string", format: "date" },
  money: { type: "number", format: "decimal" },
  reference: { type: "string", format: "id" },
};

const pascal = (s: string): string =>
  slug(s)
    .split("_")
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

const plural = (s: string): string => (s.endsWith("s") ? s : `${s}s`);

export interface CodegenReport {
  types: string;
  openapi: Record<string, unknown>;
  moduleMap: string;
  /** async event catalog (SPEC-004): the facts the system publishes. */
  events: Array<Record<string, unknown>>;
  /** reaction/event-handler stubs (SPEC-005). */
  reactionHandlers: string;
  /** RBAC permission map (SPEC-006). */
  permissions: string;
  /** workflow orchestration step-runners (SPEC-007). */
  processes: string;
  /** agent configuration (SPEC-008). */
  agents: string;
  /** application blueprint — screens per area/entity. */
  appBlueprint: string;
  /** implementation blueprint — a service per area. */
  deployBlueprint: string;
  /** MCP tool definitions (execution target). */
  mcp: string;
  /** React app scaffold (execution target). */
  react: string;
  /** what the model cannot yet express — the probe's finding (RES-001). */
  gaps: string[];
}

/** TypeScript interface per aggregate. Attributes are currently UNTYPED names → `unknown` (a gap). */
export function generateTypes(caps: CapabilityDoc, domain: DomainDoc): string {
  const lines: string[] = ["// Generated by @vbd/codegen — DO NOT EDIT. Source of truth is the model.", ""];
  for (const a of domain.aggregates) {
    lines.push(`export interface ${pascal(a.name || a.id)} {`);
    lines.push(`  id: string;`);
    for (const attr of attributeSpecs(a)) {
      const ts = attr.type ? TS_TYPE[attr.type] : "unknown";
      const note = attr.type ? "" : " // TODO: attribute type not modelled";
      lines.push(`  ${slug(attr.name)}: ${ts};${note}`);
    }
    for (const ref of a.references ?? []) lines.push(`  ${slug(ref)}Id: string; // reference → ${ref}`);
    lines.push(`}`, "");
  }
  return lines.join("\n");
}

const CREATE_VERB = /^(create|add|register|open|new|capture|issue|request|submit|plan|record)_/;

/**
 * OpenAPI 3 sketch. Reads are generic (GET list/item). WRITES are the modelled COMMANDS (SPEC-004),
 * not generic CRUD — a command becomes a real domain operation (`POST /leads/{id}/qualify_lead`),
 * carrying the events it emits in `x-emits`. Falls back to plain create/update/delete for entities
 * with no commands. Tagged by business area.
 */
export function generateOpenApi(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc): Record<string, unknown> {
  const areaOfCap = new Map<string, string>();
  for (const c of contexts?.contexts ?? []) for (const m of [...(c.capabilities ?? []), ...(c.shared_kernel ?? [])]) areaOfCap.set(m, c.name || c.id);
  const eventName = new Map((domain.events ?? []).map((e) => [e.id, e.name]));
  const cmdsOf = (aggId: string) => (domain.commands ?? []).filter((c) => c.aggregate === aggId);

  const paths: Record<string, unknown> = {};
  const schemas: Record<string, unknown> = {};
  for (const a of domain.aggregates) {
    const T = pascal(a.name || a.id);
    const res = plural(slug(a.id));
    const tag = areaOfCap.get(a.owner) ?? a.owner ?? "ungrouped";
    const props: Record<string, unknown> = { id: { type: "string" } };
    for (const attr of attributeSpecs(a)) props[slug(attr.name)] = attr.type ? OA_TYPE[attr.type] : { description: "type not modelled" };
    schemas[T] = { type: "object", properties: props };
    const ref = { $ref: `#/components/schemas/${T}` };

    const collection: Record<string, unknown> = { get: { tags: [tag], summary: `List ${T}`, responses: { "200": { description: "ok" } } } };
    const item: Record<string, unknown> = { get: { tags: [tag], summary: `Get ${T}`, responses: { "200": { description: "ok" } } } };

    const commands = cmdsOf(a.id);
    if (commands.length === 0) {
      // No behaviour modelled → generic CRUD fallback.
      (collection as Record<string, unknown>).post = { tags: [tag], summary: `Create ${T}`, requestBody: { content: { "application/json": { schema: ref } } }, responses: { "201": { description: "created" } } };
      (item as Record<string, unknown>).put = { tags: [tag], summary: `Update ${T}`, responses: { "200": { description: "ok" } } };
      (item as Record<string, unknown>).delete = { tags: [tag], summary: `Delete ${T}`, responses: { "204": { description: "deleted" } } };
    } else {
      for (const cmd of commands) {
        const action = slug(cmd.name);
        const emits = (cmd.emits ?? []).map((e) => eventName.get(e) ?? e);
        const op = {
          tags: [tag],
          summary: cmd.name,
          operationId: slug(cmd.id),
          "x-emits": emits,
          requestBody: { content: { "application/json": { schema: ref } } },
          responses: { "200": { description: emits.length ? `emits: ${emits.join(", ")}` : "ok" }, "409": { description: "command rejected" } },
        };
        if (CREATE_VERB.test(`${action}_`)) (collection as Record<string, unknown>)[`post_${action}`] = op;
        else paths[`/${res}/{id}/${action}`] = { post: op };
      }
    }
    paths[`/${res}`] = collection;
    paths[`/${res}/{id}`] = item;
  }
  return {
    openapi: "3.0.3",
    info: { title: `${caps.domain} API (scaffold)`, version: "0.0.0" },
    paths,
    components: { schemas },
  };
}

/**
 * Event catalog (SPEC-004): the async facts the system publishes — an entity's events with their
 * trigger and the commands that emit them. The seam a message bus / event log generates from.
 */
export function generateEventCatalog(domain: DomainDoc): Array<Record<string, unknown>> {
  const emittedBy = new Map<string, string[]>();
  for (const c of domain.commands ?? []) for (const e of c.emits ?? []) (emittedBy.get(e) ?? emittedBy.set(e, []).get(e)!).push(c.name);
  return (domain.events ?? []).map((e) => ({
    name: e.name,
    entity: e.aggregate,
    trigger: e.trigger ?? "command",
    emittedBy: emittedBy.get(e.id) ?? [],
  }));
}

/** A text tree: business area → capabilities → the aggregates they own. Areas as module seams. */
export function generateModuleMap(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc): string {
  const aggByOwner = new Map<string, string[]>();
  for (const a of domain.aggregates) {
    const list = aggByOwner.get(a.owner) ?? [];
    list.push(a.name || a.id);
    aggByOwner.set(a.owner, list);
  }
  const nameOfCap = new Map(caps.capabilities.map((c) => [c.id, c.name || c.id]));
  const lines: string[] = [];
  const areas = contexts?.contexts ?? [{ id: "all", name: caps.domain, intent: "", capabilities: caps.capabilities.map((c) => c.id) }];
  for (const area of areas) {
    lines.push(`module ${slug(area.id)}/  # ${area.name}`);
    for (const capId of area.capabilities ?? []) {
      lines.push(`  ${slug(capId)}/  # ${nameOfCap.get(capId) ?? capId}`);
      for (const agg of aggByOwner.get(capId) ?? []) lines.push(`    ${slug(agg)}.ts`);
    }
  }
  return lines.join("\n");
}

/**
 * Workflow/event-handler stubs (SPEC-005): each policy becomes an event handler that invokes the
 * reaction command — the cross-entity flow the behaviour layer alone couldn't generate.
 */
export function generateReactionHandlers(domain: DomainDoc): string {
  const eventName = new Map((domain.events ?? []).map((e) => [e.id, e.name]));
  const cmdName = new Map((domain.commands ?? []).map((c) => [c.id, c.name]));
  const cmdFn = (id: string): string => slug(cmdName.get(id) ?? id);
  const lines: string[] = ["// Generated by @vbd/codegen — reaction handlers (SPEC-005). Wire to your event bus.", ""];
  for (const p of domain.policies ?? []) {
    const evt = eventName.get(p.on) ?? p.on;
    lines.push(`// Policy: ${p.name}`);
    lines.push(`on(${JSON.stringify(evt)}, async (event) => {`);
    if (p.condition) lines.push(`  // if: ${p.condition}`);
    lines.push(`  await commands.${cmdFn(p.then)}({ /* from event */ });`);
    lines.push(`});`, "");
  }
  if ((domain.policies ?? []).length === 0) lines.push("// No reactions modelled yet.");
  return lines.join("\n");
}

/** Process orchestration (SPEC-007): a step-runner per workflow — the ordered command sequence. */
export function generateProcesses(domain: DomainDoc, workflows?: WorkflowsDoc): string {
  const cmdName = new Map((domain.commands ?? []).map((c) => [c.id, c.name]));
  const cmdFn = (id: string): string => slug(cmdName.get(id) ?? id);
  const lines: string[] = ["// Generated by @vbd/codegen — workflow orchestrations (SPEC-007).", ""];
  for (const w of workflows?.workflows ?? []) {
    lines.push(`export async function ${slug(w.id)}(ctx) {  // ${w.name}`);
    for (const s of w.steps ?? []) lines.push(`  await commands.${cmdFn(s)}(ctx);  // ${cmdName.get(s) ?? s}`);
    lines.push(`}`, "");
  }
  if ((workflows?.workflows ?? []).length === 0) lines.push("// No workflows modelled yet.");
  return lines.join("\n");
}

/** Agent config (SPEC-008): each agent's goal + the capability "tools" it operates. */
export function generateAgentConfig(caps: CapabilityDoc, agents?: AgentsDoc): string {
  const capName = new Map(caps.capabilities.map((c) => [c.id, c.name]));
  const lines: string[] = ["// Generated by @vbd/codegen — agent configuration (SPEC-008).", "export const agents = ["];
  for (const a of agents?.agents ?? []) {
    lines.push(`  {`);
    lines.push(`    id: ${JSON.stringify(slug(a.id))}, name: ${JSON.stringify(a.name)},`);
    lines.push(`    goal: ${JSON.stringify(a.goal ?? "")},`);
    lines.push(`    tools: [${(a.capabilities ?? []).map((c) => JSON.stringify(slug(c))).join(", ")}], // ${(a.capabilities ?? []).map((c) => capName.get(c) ?? c).join(", ")}`);
    lines.push(`  },`);
  }
  if ((agents?.agents ?? []).length === 0) lines.push("  // No agents modelled yet.");
  lines.push("];");
  return lines.join("\n");
}

/** Application blueprint (application_blueprint): screens/modules per area + entity — deterministic. */
export function generateApplicationBlueprint(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc): string {
  const areaOfCap = new Map<string, string>();
  for (const c of contexts?.contexts ?? []) for (const m of [...(c.capabilities ?? []), ...(c.shared_kernel ?? [])]) areaOfCap.set(m, c.name || c.id);
  const areas = new Map<string, string[]>();
  for (const a of domain.aggregates) {
    const area = areaOfCap.get(a.owner) ?? caps.domain;
    (areas.get(area) ?? areas.set(area, []).get(area)!).push(a.name || a.id);
  }
  const lines: string[] = ["# Application blueprint — screens grouped by business area", ""];
  for (const [area, entities] of areas) {
    lines.push(`## ${area}`);
    for (const e of entities) lines.push(`  - ${e}List (table)  ·  ${e}Detail (form)`);
    lines.push("");
  }
  return lines.join("\n").trim();
}

/** Implementation blueprint (implementation_blueprint): a service per area + its stores — deterministic. */
export function generateImplementationBlueprint(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc): string {
  const areaOfCap = new Map<string, string>();
  for (const c of contexts?.contexts ?? []) for (const m of [...(c.capabilities ?? []), ...(c.shared_kernel ?? [])]) areaOfCap.set(m, c.name || c.id);
  const svc = new Map<string, Set<string>>();
  for (const a of domain.aggregates) {
    const area = areaOfCap.get(a.owner) ?? caps.domain;
    (svc.get(area) ?? svc.set(area, new Set()).get(area)!).add(a.id);
  }
  const lines: string[] = ["# Implementation blueprint — a service per area", ""];
  for (const [area, tables] of svc) {
    const s = slug(area);
    lines.push(`service ${s}-service:`);
    lines.push(`  api: REST (/api) + events (bus)`);
    lines.push(`  datastore: db.${s} (tables: ${[...tables].join(", ")})`);
    lines.push("");
  }
  lines.push("shared: event bus, auth (RBAC from roles), workflow runner");
  return lines.join("\n").trim();
}

/**
 * RBAC permission map (SPEC-006): role → the capabilities it may operate, and the command operations
 * those imply. The seam an auth/permission layer generates from.
 */
export function generatePermissions(caps: CapabilityDoc, domain: DomainDoc, roles?: RolesDoc): string {
  const cmdsOf = (capId: string) => (domain.commands ?? []).filter((c) => c.capability === capId).map((c) => slug(c.id));
  const capName = new Map(caps.capabilities.map((c) => [c.id, c.name]));
  const lines: string[] = ["// Generated by @vbd/codegen — RBAC permission map (SPEC-006).", "export const permissions = {"];
  for (const r of roles?.roles ?? []) {
    lines.push(`  ${slug(r.id)}: {  // ${r.name}`);
    for (const capId of r.capabilities ?? []) {
      const ops = cmdsOf(capId);
      lines.push(`    ${slug(capId)}: [${ops.map((o) => `"${o}"`).join(", ")}], // ${capName.get(capId) ?? capId}`);
    }
    lines.push(`  },`);
  }
  if ((roles?.roles ?? []).length === 0) lines.push("  // No roles modelled yet.");
  lines.push("};");
  return lines.join("\n");
}

/** MCP server (execution target): each command becomes an MCP tool the agent layer can call. */
export function generateMcpTools(domain: DomainDoc): string {
  const lines: string[] = ["// Generated by @vbd/codegen — MCP tool definitions (execution target).", "export const tools = ["];
  for (const c of domain.commands ?? []) {
    lines.push(`  { name: ${JSON.stringify(slug(c.id))}, description: ${JSON.stringify(c.name)}, entity: ${JSON.stringify(c.aggregate)}, emits: [${(c.emits ?? []).map((e) => JSON.stringify(e)).join(", ")}] },`);
  }
  if ((domain.commands ?? []).length === 0) lines.push("  // No commands modelled yet.");
  lines.push("];");
  return lines.join("\n");
}

/** React app scaffold (execution target): a component per entity screen, routed by business area. */
export function generateReactApp(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc): string {
  const areaOfCap = new Map<string, string>();
  for (const c of contexts?.contexts ?? []) for (const m of [...(c.capabilities ?? []), ...(c.shared_kernel ?? [])]) areaOfCap.set(m, c.name || c.id);
  const T = (n: string) => n.split(/[^a-z0-9]+/i).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join("");
  const lines: string[] = ["// Generated by @vbd/codegen — React app scaffold (execution target).", "import { Routes, Route } from 'react-router-dom';", "", "export function App() {", "  return (", "    <Routes>"];
  for (const a of domain.aggregates) {
    const res = slug(a.id);
    lines.push(`      <Route path="/${res}s" element={<${T(a.name || a.id)}List />} />  {/* ${areaOfCap.get(a.owner) ?? caps.domain} */}`);
    lines.push(`      <Route path="/${res}s/:id" element={<${T(a.name || a.id)}Detail />} />`);
  }
  lines.push("    </Routes>", "  );", "}");
  return lines.join("\n");
}

/** Detect what the model cannot yet express — the probe's central finding (RES-001). */
export function detectGaps(caps: CapabilityDoc, domain: DomainDoc): string[] {
  const gaps: string[] = [];
  const untyped = domain.aggregates.reduce((n, a) => n + attributeSpecs(a).filter((s) => !s.type).length, 0);
  if (untyped > 0) {
    gaps.push(
      `${untyped} attributes across ${domain.aggregates.length} entities are UNTYPED → those fields emit \`unknown\`. Give them a business type (text/number/boolean/date/money/reference) for faithful schemas.`,
    );
  }
  const noAttrs = domain.aggregates.filter((a) => (a.attributes ?? []).length === 0).map((a) => a.id);
  if (noAttrs.length) gaps.push(`${noAttrs.length} entities have NO attributes (${noAttrs.join(", ")}) → empty records.`);

  const owners = new Set(domain.aggregates.map((a) => a.owner));
  const noResource = caps.capabilities.filter((c) => !owners.has(c.id)).map((c) => c.id);
  if (noResource.length) gaps.push(`${noResource.length} capabilities own no entity (${noResource.join(", ")}) → no data resource generated.`);

  const cmds = domain.commands ?? [];
  if (cmds.length === 0) {
    // No behaviour → CRUD-only (the original RES-001 gap).
    gaps.push(
      "Operations are CRUD-only: the model has no commands/events, so domain actions (e.g. \"Qualify Lead\") cannot be generated. Model the SPEC-004 behaviour layer.",
    );
  } else {
    const policies = domain.policies ?? [];
    if (policies.length === 0) {
      gaps.push(
        `${cmds.length} command operations generate, but events trigger no downstream commands — cross-entity workflows/reactions (e.g. Invoice Paid → Schedule Installation) can't be generated. This is the SPEC-005 policy/reaction layer.`,
      );
    } else {
      // Behaviour + reactions present → the full model generates (types, REST, events, reaction
      // handlers, permissions, processes, agents, app + deploy blueprints). What remains is the
      // execution *adapters*: MCP servers, a React app, GraphQL, and vertical adapters (Odoo/OpenSolar).
      gaps.push(
        `${policies.length} reaction handlers generate. The full model now projects end to end — types, REST + MCP, events, reactions, permissions, processes, agents, app + deploy blueprints, and a React scaffold. What remains is deliberately HAND-OWNED (ADR-002): vertical adapters (Odoo/OpenSolar) and the generated code's business logic.`,
      );
    }
  }
  return gaps;
}

export function generateAll(caps: CapabilityDoc, domain: DomainDoc, contexts?: ContextsDoc, roles?: RolesDoc, workflows?: WorkflowsDoc, agents?: AgentsDoc): CodegenReport {
  return {
    types: generateTypes(caps, domain),
    openapi: generateOpenApi(caps, domain, contexts),
    moduleMap: generateModuleMap(caps, domain, contexts),
    events: generateEventCatalog(domain),
    reactionHandlers: generateReactionHandlers(domain),
    permissions: generatePermissions(caps, domain, roles),
    processes: generateProcesses(domain, workflows),
    agents: generateAgentConfig(caps, agents),
    appBlueprint: generateApplicationBlueprint(caps, domain, contexts),
    deployBlueprint: generateImplementationBlueprint(caps, domain, contexts),
    mcp: generateMcpTools(domain),
    react: generateReactApp(caps, domain, contexts),
    gaps: detectGaps(caps, domain),
  };
}

export { generateApp, projectAppModel, type AppModel } from "./app.ts";
export {
  projectTargets,
  resolveBinding,
  validateBinding,
  deriveSeams,
  postgresAdapter,
  n8nAdapter,
  odooAdapter,
  ENGINES,
  POSTGRES,
  N8N,
  NODE_SPINE,
  ODOO,
  SHADCN,
  DEFAULT_BINDING,
  TECH_CAPABILITIES,
  type TechCapability,
  type Fidelity,
  type Engine,
  type Binding,
  type ResolvedElement,
  type BindingFinding,
  type Seam,
  type N8nWorkflow,
  type TargetsReport,
} from "./targets.ts";
export { shadcnAdapter, uiStructure, DEFAULT_THEME, type Theme, type UiStructure, type UiScreen } from "./ui.ts";
export { spineAdapter } from "./spine.ts";
export { mockCommunications, communicationsAdapter, type CommunicationsDoc, type CommAction, type CommChannel } from "./comms.ts";
export { mockIntegrations, integrationsAdapter, type IntegrationsDoc, type IntegrationAction, type IntegrationDirection } from "./integrations.ts";
