/**
 * @vbd/codegen/migrate — model-diff → incremental Postgres migration.
 *
 * The Postgres adapter emits a full CREATE-TABLE schema — fine for a fresh database, destructive against a
 * deployed one with data. This diffs the DEPLOYED model's domain against the NEW one and emits a migration:
 * additive changes (ADD COLUMN, CREATE TABLE, ADD FK) are applied automatically; drops and type-changes are
 * BREAKING — surfaced and emitted COMMENTED OUT, so a human decides on data preservation before applying.
 * The complete versioned model.json is the substrate: diff old vs new → the migration to grow a live app.
 *
 * Pure + isomorphic (mirrors postgresAdapter's naming/types so migrated schema == freshly-generated schema).
 */

import { slug } from "@vbd/ir";
import { attributeSpecs, type AggregateInput, type DomainDoc, type AttrType } from "@vbd/compiler";
import { PG_TYPE } from "./targets.ts";

export interface BreakingChange {
  kind: "drop_table" | "drop_column" | "change_type";
  table: string;
  column?: string;
  detail: string;
}
export interface MigrationResult {
  /** additive statements — safe to apply as-is. */
  up: string[];
  /** breaking changes — need human approval (can lose data); emitted commented in `sql`. */
  breaking: BreakingChange[];
  sql: string;
  hasChanges: boolean;
}

const pgType = (t?: AttrType): string => (t ? PG_TYPE[t] : "text");

function createTable(a: AggregateInput, tableIds: Set<string>): string {
  const cols = ["  id text PRIMARY KEY"];
  for (const attr of attributeSpecs(a)) cols.push(`  ${slug(attr.name)} ${pgType(attr.type)}`);
  for (const ref of a.references ?? []) if (tableIds.has(slug(ref))) cols.push(`  ${slug(ref)}_id text REFERENCES ${slug(ref)}(id)`);
  return `CREATE TABLE ${slug(a.id)} (\n${cols.join(",\n")}\n);`;
}

/** Diff the old domain's tables/columns against the new one → an additive-by-default migration. */
export function migratePostgres(oldDomain: DomainDoc, newDomain: DomainDoc): MigrationResult {
  const up: string[] = [];
  const breaking: BreakingChange[] = [];
  const oldById = new Map(oldDomain.aggregates.map((a) => [a.id, a]));
  const newById = new Map(newDomain.aggregates.map((a) => [a.id, a]));
  const newTableIds = new Set(newDomain.aggregates.map((a) => slug(a.id)));

  // dropped entities → breaking (a live table with data would be destroyed)
  for (const a of oldDomain.aggregates) if (!newById.has(a.id)) breaking.push({ kind: "drop_table", table: slug(a.id), detail: `entity "${a.name || a.id}" removed` });

  for (const a of newDomain.aggregates) {
    const table = slug(a.id);
    const old = oldById.get(a.id);
    if (!old) {
      up.push(createTable(a, newTableIds)); // new entity → additive
      continue;
    }
    const oldAttrs = new Map(attributeSpecs(old).map((s) => [slug(s.name), s.type]));
    const newAttrs = new Map(attributeSpecs(a).map((s) => [slug(s.name), s.type]));
    for (const [col, type] of newAttrs) {
      if (!oldAttrs.has(col)) up.push(`ALTER TABLE ${table} ADD COLUMN ${col} ${pgType(type)};`);
      else if ((oldAttrs.get(col) ?? "text") !== (type ?? "text")) breaking.push({ kind: "change_type", table, column: col, detail: `${col}: ${oldAttrs.get(col) ?? "text"} → ${type ?? "text"} (a type change may not preserve data)` });
    }
    for (const [col] of oldAttrs) if (!newAttrs.has(col)) breaking.push({ kind: "drop_column", table, column: col, detail: `column "${col}" removed` });

    const oldRefs = new Set((old.references ?? []).map((r) => slug(r)));
    const newRefs = new Set((a.references ?? []).map((r) => slug(r)));
    for (const ref of newRefs) if (!oldRefs.has(ref) && newTableIds.has(ref)) up.push(`ALTER TABLE ${table} ADD COLUMN ${ref}_id text REFERENCES ${ref}(id);`);
    for (const ref of oldRefs) if (!newRefs.has(ref)) breaking.push({ kind: "drop_column", table, column: `${ref}_id`, detail: `reference to "${ref}" removed` });
  }

  return { up, breaking, sql: renderMigration(up, breaking), hasChanges: up.length > 0 || breaking.length > 0 };
}

function breakingStmt(b: BreakingChange): string {
  if (b.kind === "drop_table") return `DROP TABLE ${b.table};`;
  if (b.kind === "drop_column") return `ALTER TABLE ${b.table} DROP COLUMN ${b.column};`;
  return `ALTER TABLE ${b.table} ALTER COLUMN ${b.column} TYPE <new type> USING ...;`; // change_type needs an explicit cast
}

function renderMigration(up: string[], breaking: BreakingChange[]): string {
  const L = [
    "-- Generated by @vbd/codegen — incremental migration (model diff).",
    "-- ADDITIVE changes below are safe to apply. BREAKING changes are commented out — review each,",
    "-- decide how to preserve/backfill data, then uncomment to apply. Never run these blind on production.",
    "",
  ];
  if (up.length) {
    L.push("-- ── Additive (safe) ──", ...up, "");
  }
  if (breaking.length) {
    L.push("-- ── BREAKING — human approval required (can LOSE DATA) ──");
    for (const b of breaking) L.push(`-- ${b.kind}: ${b.detail}`, `-- ${breakingStmt(b)}`, "");
  }
  if (!up.length && !breaking.length) L.push("-- No schema changes.");
  return L.join("\n").trim() + "\n";
}
