/**
 * Entity TypeScript types from the model — shared by the spine and the UI so both are type-safe against
 * the same shapes. Field names are snake_case to match the Postgres columns and the UI form ids; the
 * types are the source of truth a coding agent edits against. Regenerate from the model; don't hand-edit.
 */

import { slug } from "@vbd/ir";
import { attributeSpecs, type AttrType, type DomainDoc } from "@vbd/compiler";

const TS: Record<AttrType, string> = { text: "string", number: "number", boolean: "boolean", date: "string", money: "number", reference: "string" };

const pascal = (s: string): string => slug(s).split("_").filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join("");

/** Emit `export interface <Entity> { ... }` per aggregate + an EntityName union. */
export function entityTypesTs(domain: DomainDoc): string {
  const lines = ["// Generated by @vbd/codegen — entity types from the model. Regenerate; do not hand-edit.", ""];
  for (const a of domain.aggregates) {
    lines.push(`export interface ${pascal(a.name || a.id)} {`);
    lines.push(`  id: string;`);
    for (const f of attributeSpecs(a)) lines.push(`  ${slug(f.name)}?: ${f.type ? TS[f.type] : "unknown"};`);
    for (const r of a.references ?? []) lines.push(`  ${slug(r)}_id?: string;`);
    lines.push(`}`, "");
  }
  const names = domain.aggregates.map((a) => JSON.stringify(slug(a.id)));
  lines.push(`export type EntityName = ${names.length ? names.join(" | ") : "string"};`);
  return lines.join("\n");
}

/** Map an aggregate id → its interface name, for typed references in generated code. */
export function entityTypeName(domain: DomainDoc, aggId: string): string {
  const a = domain.aggregates.find((x) => x.id === aggId);
  return pascal(a?.name || aggId);
}
