/**
 * @kiln/codegen/spine — the SPINE adapter (RES-002, the `operate` engine made real).
 *
 * The spine is the command API the UI, n8n, and Odoo all call — the hub that owns the operations and is
 * the only thing that touches the stores. It's a RUNNABLE, TYPE-SAFE TypeScript service (Express + pg):
 * one route per command, backed by Postgres, emitting events (and POSTing them to n8n — the seam).
 *
 * Per-command LOGIC is a pure `(input, ctx) => record` handler, LLM-DRAFTED (generateAppLogic, security-
 * validated) and spliced here via a typed `h<Entity>(...)` wrapper so `input` reads the entity's typed
 * fields. Missing → a safe pass-through default, so the service always boots. tsc + eslint keep it honest.
 *
 * Pure and isomorphic (emits code as strings; no node:* at generation time).
 */

import { slug } from "@kiln/ir";
import { attributeSpecs, type CapabilityDoc, type DomainDoc } from "@kiln/compiler";
import { entityTypesTs, entityTypeName } from "./model-types.ts";

const CREATE_VERB = /^(create|add|register|open|new|capture|issue|request|submit|plan|record)_/;

interface Route {
  command: string;
  name: string;
  method: string;
  path: string;
  entity: string;
  table: string;
  create: boolean;
  emits: string[];
}

/**
 * Per-entity field→type map from the model's typed attributes — the source of truth for input validation.
 * Keyed by aggregate slug (matches `columns` + the routes' `entity`). `id` and references are id strings;
 * untyped attributes map to "any" (no constraint). Pure — exported so the mapping is unit-tested directly.
 */
export function entityFieldTypes(domain: DomainDoc): Record<string, Record<string, string>> {
  const out: Record<string, Record<string, string>> = {};
  for (const a of domain.aggregates) {
    const fields: Record<string, string> = { id: "text" };
    for (const f of attributeSpecs(a)) fields[slug(f.name)] = f.type ?? "any";
    for (const r of a.references ?? []) fields[`${slug(r)}_id`] = "reference";
    out[slug(a.id)] = fields;
  }
  return out;
}

function routesFor(domain: DomainDoc): Route[] {
  const evName = new Map((domain.events ?? []).map((e) => [e.id, slug(e.id)]));
  return (domain.commands ?? []).map((c) => {
    const res = `${slug(c.aggregate)}s`;
    const action = slug(c.name || c.id);
    const create = CREATE_VERB.test(`${action}_`);
    return {
      command: slug(c.id),
      name: c.name || c.id,
      method: "POST",
      path: create ? `/${res}` : `/${res}/{id}/${action}`,
      entity: c.aggregate,
      table: slug(c.aggregate),
      create,
      emits: (c.emits ?? []).map((e) => evName.get(e) ?? slug(e)),
    };
  });
}

/**
 * The most rows a FILTERED read hands back, and the ceiling an explicit `?limit=` may ask for. Matches the
 * agent runtime's `READ_ROW_CAP` by construction (the agent's `find_<entity>` tool is the main caller), so
 * a filter that happens to match the whole table still can't dump it.
 */
export const READ_LIMIT_CAP = 50;

/**
 * The generated `src/query.ts` — read-filter parsing + parameterised SQL, shared by `app.ts` (parse) and
 * `db.ts` (SQL). Self-contained + dialect-neutral: the placeholder style is passed in, so ONE implementation
 * serves both Postgres (`$1`) and SQLite (`?`).
 *
 * **The safety property, by construction:** a request param NEVER reaches the SQL string. `plan()` keeps only
 * keys present in the entity's GENERATED column list (an allow-list derived from the model, not the request);
 * `filterSql()` re-applies that allow-list at the SQL seam and binds every value — and the limit — as a
 * placeholder. Column names are concatenated only after passing the allow-list; values never are.
 */
const QUERY_TS = `// Generated by @kiln/codegen spine — read-filter parsing + parameterised SQL. Regenerate from the model.
//
// SAFETY: a request param NEVER reaches the SQL string.
//  · plan()      keeps only keys that are in the entity's generated column list (an ALLOW-LIST from the
//                model, not from the request). Anything else is reported as an error, never guessed at.
//  · filterSql() re-applies that allow-list at the SQL seam, concatenates only allow-listed column names,
//                and binds every value AND the limit as placeholders.
// Deliberately boring: exact match only (AND across fields) — no operators, no OR, no LIKE, no sorting.
export const READ_LIMIT_CAP = ${READ_LIMIT_CAP};

export interface ReadPlan {
  /** allow-listed column → exact-match value. */
  where: Record<string, string>;
  /** rows to return, clamped to READ_LIMIT_CAP (an explicit ?limit= may only ever ask for FEWER). */
  limit: number;
  /** human-readable rejections ([] = the query is usable). */
  errors: string[];
  /** did the caller actually ask to narrow? (no → the route keeps its unfiltered list-everything behaviour) */
  filtered: boolean;
}

/** Parse \`GET /<res>?<column>=<value>&limit=<n>\` against the entity's real columns. */
export function plan(query: Record<string, unknown>, cols: string[]): ReadPlan {
  const allowed = new Set(cols);
  const where: Record<string, string> = {};
  const errors: string[] = [];
  let limit = READ_LIMIT_CAP;
  let asked = false;
  for (const [key, raw] of Object.entries(query ?? {})) {
    const value = Array.isArray(raw) ? raw[0] : raw; // ?f=a&f=b → first wins (no implicit OR)
    if (key === "limit") {
      const n = Number(value);
      if (!Number.isFinite(n) || n < 1) { errors.push("limit must be a positive integer"); continue; }
      limit = Math.min(Math.floor(n), READ_LIMIT_CAP);
      asked = true;
      continue;
    }
    if (!allowed.has(key)) { errors.push("unknown filter field " + JSON.stringify(key)); continue; }
    if (value === undefined || value === null) { errors.push(key + " needs a value"); continue; }
    where[key] = String(value);
  }
  return { where, limit, errors, filtered: asked || Object.keys(where).length > 0 };
}

/**
 * Build the parameterised SELECT. \`table\` + the column names come from the GENERATED model facts (schema.ts),
 * never from the request; \`ph\` yields the dialect's placeholder ("$1" for pg, "?" for SQLite).
 */
export function filterSql(table: string, cols: string[], where: Record<string, string>, limit: number, ph: (i: number) => string): { sql: string; params: unknown[] } {
  const keys = Object.keys(where).filter((k) => cols.includes(k)); // allow-list, re-checked at the SQL seam
  const params: unknown[] = keys.map((k) => where[k]);             // every value is BOUND, never concatenated
  const clause = keys.length ? " WHERE " + keys.map((k, i) => k + " = " + ph(i + 1)).join(" AND ") : "";
  params.push(Math.max(1, Math.min(Math.floor(Number(limit)) || READ_LIMIT_CAP, READ_LIMIT_CAP)));
  return { sql: "SELECT * FROM " + table + clause + " LIMIT " + ph(params.length), params };
}
`;

/**
 * Spine adapter. `handlers` maps a command id → an LLM-drafted `(input, ctx) => record` arrow source
 * (from generateAppLogic, already security-validated). Missing → a pass-through default.
 */
// SQLite column type per business attribute type (matches targets.ts SQLITE_TYPE; kept local to avoid a cycle).
const SPINE_SQLITE_TYPE: Record<string, string> = { text: "TEXT", number: "REAL", boolean: "INTEGER", date: "TEXT", money: "NUMERIC", reference: "TEXT" };

/** CREATE TABLE IF NOT EXISTS for every aggregate — the spine embeds this to auto-create its store on boot
 *  (idempotent → safe every start). No FK ordering needed: SQLite validates references only at insert time. */
function sqliteSchema(domain: DomainDoc): string {
  const ids = new Set(domain.aggregates.map((a) => a.id));
  return domain.aggregates
    .map((a) => {
      const cols = [
        "  id TEXT PRIMARY KEY",
        ...attributeSpecs(a).map((attr) => `  ${slug(attr.name)} ${attr.type ? SPINE_SQLITE_TYPE[attr.type] ?? "TEXT" : "TEXT"}`),
        ...(a.references ?? []).filter((ref) => ids.has(ref)).map((ref) => `  ${slug(ref)}_id TEXT REFERENCES ${slug(ref)}(id)`),
      ];
      return `CREATE TABLE IF NOT EXISTS ${slug(a.id)} (\n${cols.join(",\n")}\n);`;
    })
    .join("\n");
}

export function spineAdapter(_caps: CapabilityDoc, domain: DomainDoc, handlers: Record<string, string> = {}, dialect: "postgres" | "sqlite" = "postgres"): Record<string, string> {
  const commands = domain.commands ?? [];
  if (!commands.length) return {};
  const sqlite = dialect === "sqlite";
  const schemaSql = sqlite ? sqliteSchema(domain) : "";
  const routes = routesFor(domain);
  const columns: Record<string, string[]> = {};
  for (const a of domain.aggregates) columns[slug(a.id)] = ["id", ...attributeSpecs(a).map((f) => slug(f.name)), ...(a.references ?? []).map((r) => `${slug(r)}_id`)];

  const schemaTs = [
    "// Generated by @kiln/codegen spine — model facts (routes + columns). Regenerate from model.json.",
    `export const columns: Record<string, string[]> = ${JSON.stringify(columns, null, 2)};`,
    `export interface Route { command: string; method: string; path: string; table: string; entity: string; create: boolean; emits: string[]; }`,
    `export const routes: Route[] = ${JSON.stringify(routes.map((r) => ({ command: r.command, method: r.method, path: r.path, table: r.table, entity: slug(r.entity), create: r.create, emits: r.emits })), null, 2)};`,
  ].join("\n\n");

  // validate.ts — deterministic input validation from the model's typed attributes. Type-checks the fields
  // that ARE present (partial updates stay valid); unknown/untyped fields pass. Runs before each handler.
  const validateTs = `// Generated by @kiln/codegen spine — request input validation from the model's typed attributes.
// Type-checks only the fields PRESENT in the body (partial updates are valid); unknown/untyped fields pass.
export const fieldTypes: Record<string, Record<string, string>> = ${JSON.stringify(entityFieldTypes(domain), null, 2)};

function ok(type: string, v: unknown): boolean {
  switch (type) {
    case "text":
    case "reference": return typeof v === "string";
    case "number":
    case "money": return typeof v === "number" && Number.isFinite(v);
    case "boolean": return typeof v === "boolean";
    case "date": return typeof v === "string" && !Number.isNaN(Date.parse(v));
    default: return true; // "any" / untyped — no constraint
  }
}

// Returns a list of human-readable errors ([] = valid). \`entity\` is the aggregate slug (routes[].entity).
export function validate(entity: string, body: unknown): string[] {
  if (body === null || typeof body !== "object" || Array.isArray(body)) return ["body must be a JSON object"];
  const types = fieldTypes[entity] ?? {};
  const errors: string[] = [];
  for (const [k, v] of Object.entries(body as Record<string, unknown>)) {
    if (v === null || v === undefined) continue; // absent / cleared — allowed
    const t = types[k];
    if (t && !ok(t, v)) errors.push(k + " must be " + (t === "reference" ? "a reference id (string)" : t));
  }
  return errors;
}
`;

  // handlers.ts — LLM-drafted (block-bodied, heavily commented) where available; pass-through otherwise.
  // The note goes ABOVE each entry so a multi-line commented body's trailing comma is never swallowed.
  const handlerEntries = routes.map((r) => {
    const drafted = handlers[r.command];
    const isDraft = Boolean(drafted && /=>/.test(drafted));
    const type = entityTypeName(domain, r.entity);
    const fn = isDraft ? drafted.trim() : "(input) => ({ ...input })";
    const note = isDraft
      ? `  // ${r.name} — LLM-drafted; the inline comments below explain each decision and why.`
      : `  // ${r.name} — pass-through default. TODO: implement the real business logic here.`;
    // h<Entity>(...) types `input` to the entity so drafted logic reads typed fields.
    return `${note}\n  ${JSON.stringify(r.command)}: h<T.${type}>(${fn}),`;
  });
  const handlersTs = [
    "// Generated by @kiln/codegen spine — command logic `(input, ctx) => record`.",
    "// LLM-drafted bodies are heavily commented with the reasoning; pass-throughs are yours to fill.",
    "// The runtime (server.ts) persists the returned record and emits the command's events around this.",
    'import type * as T from "./types";',
    'import { h, type Handler } from "./runtime";',
    "",
    "export const handlers: Record<string, Handler> = {",
    ...handlerEntries,
    "};",
  ].join("\n");

  return {
    "package.json": JSON.stringify(
      {
        name: "generated-spine",
        private: true,
        type: "module",
        packageManager: "pnpm@9.12.0",
        engines: { node: ">=20" },
        scripts: { start: "tsx src/server.ts", dev: "tsx watch src/server.ts", typecheck: "tsc --noEmit", lint: "eslint src", test: "node --import tsx --test test/*.test.ts" },
        dependencies: sqlite ? { express: "^4.21.0", "better-sqlite3": "^11.3.0" } : { express: "^4.21.0", pg: "^8.13.0" },
        devDependencies: { tsx: "^4.19.0", typescript: "^5.6.2", "@types/express": "^4.17.21", ...(sqlite ? { "@types/better-sqlite3": "^7.6.11" } : { "@types/pg": "^8.11.10" }), "@types/node": "^20.16.5", eslint: "^9.11.0", "@eslint/js": "^9.11.0", "typescript-eslint": "^8.6.0", globals: "^15.9.0" },
      },
      null,
      2,
    ),
    "tsconfig.json": JSON.stringify(
      { compilerOptions: { target: "ES2022", module: "ESNext", moduleResolution: "bundler", strict: true, noEmit: true, esModuleInterop: true, skipLibCheck: true, lib: ["ES2022", "DOM"], types: ["node"] }, include: ["src", "test"] },
      null,
      2,
    ),
    "eslint.config.js": `import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";
export default tseslint.config(js.configs.recommended, ...tseslint.configs.recommended, {
  languageOptions: { globals: { ...globals.node } },
  rules: {
    "@typescript-eslint/no-explicit-any": "warn",
    // handlers have a fixed (input, ctx) signature — a body may legitimately use only one.
    "@typescript-eslint/no-unused-vars": ["error", { args: "none", varsIgnorePattern: "^_" }],
  },
});
`,
    ".env.example": sqlite
      ? "# Copy to .env — the command API's config.\nPORT=3000\nDB_FILE=data/app.db\n\n# API auth — set a shared bearer token to require `Authorization: Bearer <token>` on all command routes\n# (leave unset for local dev = OPEN; the boot warns). Internal callers (the UI, n8n HTTP nodes, agents) must\n# send the SAME token. /health stays open.\n# API_TOKEN=change-me\n\n# optional: POST emitted events to n8n webhooks (on/<event>). Point at a remote n8n by changing the URL.\nN8N_BASE_URL=http://localhost:5678/webhook\n# if the remote n8n webhooks use Header Auth, set the bearer token:\n# N8N_WEBHOOK_TOKEN=\n"
      : "# Copy to .env — the command API's config.\nPORT=3000\n\n# API auth — set a shared bearer token to require `Authorization: Bearer <token>` on all command routes\n# (leave unset for local dev = OPEN; the boot warns). Internal callers (the UI, n8n HTTP nodes, agents) must\n# send the SAME token. /health stays open.\n# API_TOKEN=change-me\n\n# Postgres — change host/user/password for a REMOTE/managed db. For managed Postgres (Supabase/Neon/RDS),\n# use TLS: append ?sslmode=require to the URL, or set PGSSL=require (verified). PGSSL=no-verify is dev-only.\nDATABASE_URL=postgres://app:app@localhost:5432/app\n# PGSSL=require\n\n# optional: POST emitted events to n8n webhooks (on/<event>). Point at a remote n8n by changing the URL.\nN8N_BASE_URL=http://localhost:5678/webhook\n# if the remote n8n webhooks use Header Auth, set the bearer token:\n# N8N_WEBHOOK_TOKEN=\n",
    "README.md": `# Generated spine (command API)

The \`operate\` engine: one HTTP route per command, backed by Postgres, emitting events (and POSTing them
to n8n when \`N8N_BASE_URL\` is set — the seam). The UI / n8n / Odoo all call this. TypeScript, \`strict\`.

\`\`\`bash
pnpm install
pnpm typecheck   # tsc --noEmit
pnpm lint        # eslint
pnpm start       # tsx src/server.ts → http://localhost:3000
\`\`\`

Logic lives in \`src/handlers.ts\` as \`h<Entity>((input, ctx) => record)\` — \`input\` is typed to the
entity. LLM-drafted where possible; fill the pass-through defaults. Structure (routes, columns, types)
is generated — regenerate from the model, don't hand-edit.

## Reading records

- \`GET /<entity>s\` — every row (what the UI lists).
- \`GET /<entity>s/:id\` — one record.
- \`GET /<entity>s?<field>=<value>\` — the records matching **exactly** on that field; repeat the param name
  for more fields (they AND together), e.g. \`/leads?email=a@b.com&status=new\`. Only the entity's own
  columns are filterable — anything else is a \`400\` listing the fields that are. Exact match only (no
  operators/OR/LIKE), capped at ${READ_LIMIT_CAP} rows; \`?limit=<n>\` may ask for fewer. This is how an agent checks
  "is this email already a lead?" without pulling the whole table.

## Auth & input validation

- **Auth** — set \`API_TOKEN\` to require \`Authorization: Bearer <token>\` on every command route (unset =
  OPEN, a boot warning nags). \`/health\` stays open for probes. When set, internal callers (the UI, n8n
  HTTP nodes, the agents runtime) must send the same token. The compare is constant-time.
- **Validation** — \`src/validate.ts\` type-checks each request body against the model's typed attributes
  (only the fields present — partial updates stay valid; unknown/untyped fields pass). A bad field →
  \`400 { error, details }\` before any handler or DB work. Regenerated from the model — don't hand-edit.
`,
    "src/types.ts": entityTypesTs(domain),
    "src/runtime.ts": `// Runtime contracts shared by handlers + server.
export type Ctx = {
  all: (entity: string) => Promise<Record<string, unknown>[]>;
  find: (entity: string, id: string) => Promise<Record<string, unknown> | undefined>;
};
export type Handler = (input: Record<string, unknown>, ctx: Ctx) => Record<string, unknown> | Promise<Record<string, unknown>>;
// Wrap a drafted handler so \`input\` reads the entity's typed fields, while the boundary stays a Handler.
export const h = <E>(fn: (input: Partial<E> & Record<string, unknown>, ctx: Ctx) => Record<string, unknown> | Promise<Record<string, unknown>>): Handler => fn as Handler;
`,
    "src/query.ts": QUERY_TS,
    "src/db.ts": sqlite
      ? `import Database from "better-sqlite3";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { filterSql } from "./query";
// Embedded, file-based store — one file, no separate db service. better-sqlite3 is synchronous; we keep the
// same async interface as the Postgres driver so the rest of the spine is identical. Tables are auto-created
// on boot (idempotent), so the app runs with no manual schema step. sqlite/schema.sql stays for reference.
const file = process.env.DB_FILE || "data/app.db";
mkdirSync(dirname(file), { recursive: true });
const db = new Database(file);
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");
db.exec(${JSON.stringify(schemaSql)});
// SQLite params must be primitives — coerce booleans (0/1) and objects (JSON).
const norm = (v: unknown): unknown => (typeof v === "boolean" ? (v ? 1 : 0) : v !== null && typeof v === "object" ? JSON.stringify(v) : v);
export function genId(): string { return "r_" + Math.random().toString(36).slice(2, 10); }
export async function insert(table: string, cols: string[], record: Record<string, unknown>): Promise<Record<string, unknown>> {
  const r: Record<string, unknown> = { ...record };
  if (!r.id) r.id = genId();
  const keys = cols.filter((c) => c in r);
  const ph = keys.map(() => "?").join(", ");
  const upd = keys.filter((c) => c !== "id").map((c) => c + "=excluded." + c).join(", ") || "id=excluded.id";
  db.prepare("INSERT INTO " + table + " (" + keys.join(", ") + ") VALUES (" + ph + ") ON CONFLICT(id) DO UPDATE SET " + upd).run(...keys.map((k) => norm(r[k])));
  return r;
}
export async function update(table: string, id: string, cols: string[], record: Record<string, unknown>): Promise<Record<string, unknown>> {
  const keys = cols.filter((c) => c in record && c !== "id");
  if (keys.length) db.prepare("UPDATE " + table + " SET " + keys.map((c) => c + "=?").join(", ") + " WHERE id=?").run(...keys.map((k) => norm(record[k])), id);
  return { id, ...record };
}
export const all = async (table: string): Promise<Record<string, unknown>[]> => db.prepare("SELECT * FROM " + table).all() as Record<string, unknown>[];
export const find = async (table: string, id: string): Promise<Record<string, unknown> | undefined> => db.prepare("SELECT * FROM " + table + " WHERE id=?").get(id) as Record<string, unknown> | undefined;
// Look records up BY FIELD VALUE (exact match, AND) instead of listing the table and scanning it. \`cols\` is
// the entity's generated column list — filterSql treats it as the allow-list and binds every value.
export const filter = async (table: string, cols: string[], where: Record<string, string>, limit: number): Promise<Record<string, unknown>[]> => {
  const q = filterSql(table, cols, where, limit, () => "?");
  return db.prepare(q.sql).all(...q.params.map(norm)) as Record<string, unknown>[];
};
`
      : `import pg from "pg";
import { filterSql } from "./query";
const DATABASE_URL = process.env.DATABASE_URL || "postgres://app:app@localhost:5432/app";
// Managed Postgres (Supabase, Neon, RDS…) needs TLS. PGSSL=require (or ?sslmode=require in the URL) →
// VERIFIED TLS. PGSSL=no-verify skips cert verification (dev/self-signed only — allows MITM; avoid in prod).
const ssl = process.env.PGSSL === "no-verify" ? { rejectUnauthorized: false } : process.env.PGSSL === "require" || /sslmode=require/.test(DATABASE_URL) ? true : undefined;
export const pool = new pg.Pool({ connectionString: DATABASE_URL, ssl });
export function genId(): string { return "r_" + Math.random().toString(36).slice(2, 10); }
export async function insert(table: string, cols: string[], record: Record<string, unknown>): Promise<Record<string, unknown>> {
  const r: Record<string, unknown> = { ...record };
  if (!r.id) r.id = genId();
  const keys = cols.filter((c) => c in r);
  const ph = keys.map((_v, i) => "$" + (i + 1)).join(", ");
  const upd = keys.filter((c) => c !== "id").map((c) => c + "=EXCLUDED." + c).join(", ") || "id=EXCLUDED.id";
  await pool.query("INSERT INTO " + table + " (" + keys.join(", ") + ") VALUES (" + ph + ") ON CONFLICT (id) DO UPDATE SET " + upd, keys.map((k) => r[k]));
  return r;
}
export async function update(table: string, id: string, cols: string[], record: Record<string, unknown>): Promise<Record<string, unknown>> {
  const keys = cols.filter((c) => c in record && c !== "id");
  if (keys.length) await pool.query("UPDATE " + table + " SET " + keys.map((c, i) => c + "=$" + (i + 2)).join(", ") + " WHERE id=$1", [id, ...keys.map((k) => record[k])]);
  return { id, ...record };
}
export const all = (table: string): Promise<Record<string, unknown>[]> => pool.query("SELECT * FROM " + table).then((r) => r.rows as Record<string, unknown>[]);
export const find = (table: string, id: string): Promise<Record<string, unknown> | undefined> => pool.query("SELECT * FROM " + table + " WHERE id=$1", [id]).then((r) => r.rows[0] as Record<string, unknown> | undefined);
// Look records up BY FIELD VALUE (exact match, AND) instead of listing the table and scanning it. \`cols\` is
// the entity's generated column list — filterSql treats it as the allow-list and binds every value.
export const filter = (table: string, cols: string[], where: Record<string, string>, limit: number): Promise<Record<string, unknown>[]> => {
  const q = filterSql(table, cols, where, limit, (i) => "$" + i);
  return pool.query(q.sql, q.params).then((r) => r.rows as Record<string, unknown>[]);
};
`,
    "src/events.ts": `const N8N = process.env.N8N_BASE_URL;
const N8N_TOKEN = process.env.N8N_WEBHOOK_TOKEN; // optional — secure a REMOTE n8n's webhook (Header Auth)
// Emit a domain event: log it, and (if configured) POST to the n8n webhook the generated workflow listens on.
export async function emit(name: string, payload: Record<string, unknown>): Promise<void> {
  console.log("[event] " + name + " " + (payload && payload.id ? String(payload.id) : ""));
  if (N8N) {
    try {
      const headers: Record<string, string> = { "content-type": "application/json" };
      if (N8N_TOKEN) headers.authorization = "Bearer " + N8N_TOKEN;
      await fetch(N8N + "/on/" + name, { method: "POST", headers, body: JSON.stringify(payload || {}) });
    } catch (e) {
      console.warn("emit->n8n failed: " + (e as Error).message);
    }
  }
}
`,
    "src/handlers.ts": handlersTs,
    "src/schema.ts": schemaTs,
    "src/validate.ts": validateTs,
    "src/app.ts": `import express, { type Request, type Response, type NextFunction, type Express } from "express";
import { timingSafeEqual } from "node:crypto";
import { insert, update, all, find, filter } from "./db";
import { emit } from "./events";
import { handlers } from "./handlers";
import { columns, routes } from "./schema";
import { validate } from "./validate";
import { plan } from "./query";
import type { Ctx } from "./runtime";

// Opt-in bearer auth: set API_TOKEN to require \`Authorization: Bearer <token>\` on every command route.
// Unset = OPEN (fine for local dev; the boot warning nags). Internal callers (the UI, n8n HTTP nodes, the
// agents runtime) must send the SAME token when it is set. /health stays open for liveness probes.
const API_TOKEN = process.env.API_TOKEN;
function bearerOk(header: string | undefined): boolean {
  if (!API_TOKEN) return true; // open mode
  const token = header && header.startsWith("Bearer ") ? header.slice(7) : "";
  if (!token) return false;
  const a = Buffer.from(token), b = Buffer.from(API_TOKEN);
  return a.length === b.length && timingSafeEqual(a, b); // constant-time compare (avoid length/value leak)
}
function requireAuth(req: Request, res: Response, next: NextFunction): void {
  if (bearerOk(req.header("authorization"))) { next(); return; }
  res.status(401).json({ error: "unauthorized" });
}

// The Express app, exported so tests can exercise it without opening a port (see test/).
export function createApp(): Express {
  const app = express();
  app.use(express.json());
  // CORS — the generated UI is a separate origin (Vite dev, or a static host in prod), so it must be
  // allowed to call this API. Permissive by default; tighten Access-Control-Allow-Origin for production.
  app.use((req: Request, res: Response, next: NextFunction) => {
    res.header("Access-Control-Allow-Origin", process.env.CORS_ORIGIN || "*");
    res.header("Access-Control-Allow-Headers", "content-type, authorization");
    res.header("Access-Control-Allow-Methods", "GET,POST,PUT,DELETE,OPTIONS");
    if (req.method === "OPTIONS") { res.sendStatus(204); return; }
    next();
  });
  if (!API_TOKEN) console.warn("[auth] API_TOKEN is not set — the command API is OPEN (no auth). Set API_TOKEN before exposing it beyond localhost.");
  app.get("/health", (_req: Request, res: Response) => { res.json({ ok: true }); });

  // ctx gives handlers read access to the stores without touching SQL.
  const ctx: Ctx = { all, find };

  // Read endpoints (list + by id) so a UI can render data — the command routes below are the write side.
  // Same opt-in bearer auth as writes; entity == table (both the aggregate slug). Keep them before the
  // command routes so a command path can't shadow a read.
  for (const entity of Object.keys(columns)) {
    const res = entity + "s"; // match the command routes' plural resource (POST /<entity>s creates)
    // GET /<res>                      → every row (unchanged: the UI lists the table)
    // GET /<res>?<column>=<value>     → the rows matching EXACTLY on the entity's own columns (AND across
    //                                   fields), capped at READ_LIMIT_CAP — so "is this email already a
    //                                   lead?" is one query, not a full-table scan by the caller.
    // An unknown param is a 400 (with the filterable fields) — never silently ignored, so a typo'd filter
    // can't read as "no matches". See query.ts for the allow-list + parameterisation.
    app.get("/" + res, requireAuth, async (req: Request, response: Response) => {
      const cols = columns[entity];
      const p = plan(req.query as Record<string, unknown>, cols);
      if (p.errors.length) { response.status(400).json({ error: "bad query", details: p.errors, filterable: cols }); return; }
      response.json(p.filtered ? await filter(entity, cols, p.where, p.limit) : await all(entity));
    });
    app.get("/" + res + "/:id", requireAuth, async (req: Request, response: Response) => {
      const row = await find(entity, req.params.id);
      if (row) response.json(row); else response.status(404).json({ error: "not found" });
    });
  }

  for (const r of routes) {
    const path = r.path.replace("{id}", ":id");
    app.post(path, requireAuth, async (req: Request, res: Response) => {
      try {
        const errors = validate(r.entity, req.body); // reject malformed input before any handler/DB work
        if (errors.length) { res.status(400).json({ error: "validation failed", details: errors }); return; }
        const input: Record<string, unknown> = { ...req.body, ...(req.params.id ? { id: req.params.id } : {}) };
        const handler = handlers[r.command] ?? ((i: Record<string, unknown>) => ({ ...i }));
        const draft = (await handler(input, ctx)) ?? input;
        const record = r.create ? await insert(r.table, columns[r.entity], draft) : await update(r.table, req.params.id, columns[r.entity], draft);
        for (const ev of r.emits) await emit(ev, record);
        res.status(r.create ? 201 : 200).json(record);
      } catch (e) {
        res.status(422).json({ error: String((e as Error)?.message ?? e) });
      }
    });
  }
  return app;
}

export const routeCount = routes.length;
`,
    "src/server.ts": `import { createApp, routeCount } from "./app";
const port = process.env.PORT || 3000;
createApp().listen(port, () => console.log("spine listening on :" + port + " (" + routeCount + " command routes)"));
`,
    "test/handlers.test.ts": `import { test } from "node:test";
import assert from "node:assert/strict";
import { handlers } from "../src/handlers";

const ctx = { all: async () => [], find: async () => undefined };

test("every command has a handler", () => {
  assert.ok(Object.keys(handlers).length > 0);
});

test("a handler returns a record that carries the input fields", async () => {
  const cmd = Object.keys(handlers)[0];
  const out = await handlers[cmd]({ id: "x1", note: "hello" }, ctx);
  assert.equal(typeof out, "object");
  assert.equal((out as Record<string, unknown>).note, "hello"); // pass-through / spread preserves input
});
`,
    "Dockerfile": `FROM node:20-alpine
WORKDIR /app
RUN corepack enable
COPY package.json ./
RUN pnpm install --no-frozen-lockfile
COPY . .
EXPOSE 3000
CMD ["pnpm", "start"]
`,
    ".dockerignore": "node_modules\n.env\n",
  };
}
