/**
 * @vbd/codegen/spine — the SPINE adapter (RES-002, the `operate` engine made real).
 *
 * The spine is the command API the UI, n8n, and Odoo all call — the hub that owns the operations and
 * is the only thing that touches the stores. Until now it was a concept; this emits it as a RUNNABLE
 * Node/Express service: one route per command, backed by Postgres, emitting events (and POSTing them to
 * n8n — the seam, materialized).
 *
 * The per-command LOGIC is a pure `(input, ctx) => record` handler. Those are LLM-DRAFTED (the existing
 * generateAppLogic skill, security-validated) and spliced in here; any command without a draft gets a
 * safe pass-through default, so the service always boots. "The model proposes; validators + human decide."
 *
 * Pure and isomorphic (emits code as strings; no node:* at generation time).
 */

import { slug } from "@vbd/ir";
import { attributeSpecs, type CapabilityDoc, type DomainDoc } from "@vbd/compiler";

const CREATE_VERB = /^(create|add|register|open|new|capture|issue|request|submit|plan|record)_/;

interface Route {
  command: string;
  name: string;
  method: string;
  path: string;
  entity: string;
  table: string;
  create: boolean;
  emits: string[];
}

function routesFor(domain: DomainDoc): Route[] {
  const evName = new Map((domain.events ?? []).map((e) => [e.id, slug(e.id)]));
  return (domain.commands ?? []).map((c) => {
    const res = `${slug(c.aggregate)}s`;
    const action = slug(c.name || c.id);
    const create = CREATE_VERB.test(`${action}_`);
    return {
      command: slug(c.id),
      name: c.name || c.id,
      method: "POST",
      path: create ? `/${res}` : `/${res}/{id}/${action}`,
      entity: c.aggregate,
      table: slug(c.aggregate),
      create,
      emits: (c.emits ?? []).map((e) => evName.get(e) ?? slug(e)),
    };
  });
}

/**
 * Spine adapter. `handlers` maps a command id → an LLM-drafted `(input, ctx) => record` arrow function
 * source (from generateAppLogic, already security-validated). Missing → a pass-through default.
 */
export function spineAdapter(caps: CapabilityDoc, domain: DomainDoc, handlers: Record<string, string> = {}): Record<string, string> {
  const commands = domain.commands ?? [];
  if (!commands.length) return {};
  const routes = routesFor(domain);
  const columns: Record<string, string[]> = {};
  for (const a of domain.aggregates) columns[slug(a.id)] = ["id", ...attributeSpecs(a).map((f) => slug(f.name)), ...(a.references ?? []).map((r) => `${slug(r)}_id`)];

  // schema.js — the model facts the runtime needs (routes, columns per table).
  const schemaJs = [
    "// Generated by @vbd/codegen spine — model facts (routes + columns). Regenerate from model.json.",
    `export const columns = ${JSON.stringify(columns, null, 2)};`,
    `export const routes = ${JSON.stringify(routes.map((r) => ({ command: r.command, method: r.method, path: r.path, table: r.table, entity: slug(r.entity), create: r.create, emits: r.emits })), null, 2)};`,
  ].join("\n\n");

  // handlers.js — the per-command business logic. LLM-drafted where available; pass-through otherwise.
  const handlerEntries = routes.map((r) => {
    const drafted = handlers[r.command];
    const fn = drafted && /=>/.test(drafted) ? drafted.trim() : "(input) => ({ ...input })";
    const note = drafted ? "// LLM-drafted" : "// TODO: pass-through default — replace with real business logic";
    return `  ${JSON.stringify(r.command)}: ${fn}, ${note}`;
  });
  const handlersJs = ["// Generated by @vbd/codegen spine — command logic `(input, ctx) => record`.", "// Drafted by the LLM where available; edit here to add/adjust business rules.", "export const handlers = {", ...handlerEntries, "};"].join("\n");

  return {
    "package.json": JSON.stringify(
      { name: "generated-spine", private: true, type: "module", packageManager: "pnpm@9.12.0", scripts: { start: "node src/server.js", dev: "node --watch src/server.js" }, dependencies: { express: "^4.21.0", pg: "^8.13.0" } },
      null,
      2,
    ),
    ".env.example": "# Copy to .env\nPORT=3000\nDATABASE_URL=postgres://app:app@localhost:5432/app\n# optional: POST emitted events to n8n webhooks (on/<event>)\nN8N_BASE_URL=http://localhost:5678/webhook\n",
    "README.md": `# Generated spine (command API)

The \`operate\` engine: one HTTP route per command, backed by Postgres, emitting events (and POSTing them
to n8n when \`N8N_BASE_URL\` is set — the seam). The UI / n8n / Odoo all call this.

\`\`\`bash
pnpm install
pnpm start   # http://localhost:3000  (POST /health to check)
\`\`\`

Logic lives in \`src/handlers.js\` as \`(input, ctx) => record\` — LLM-drafted where possible; fill the
pass-through defaults with real rules. Structure (routes, columns) comes from \`schema.js\`; regenerate it
from the model, don't hand-edit.
`,
    "src/db.js": `import pg from "pg";
export const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL || "postgres://app:app@localhost:5432/app" });
export function genId() { return "r_" + Math.random().toString(36).slice(2, 10); }
export async function insert(table, cols, record) {
  const r = { ...record }; if (!r.id) r.id = genId();
  const keys = cols.filter((c) => c in r);
  const ph = keys.map((_, i) => "$" + (i + 1)).join(", ");
  const upd = keys.filter((c) => c !== "id").map((c) => c + "=EXCLUDED." + c).join(", ") || "id=EXCLUDED.id";
  await pool.query("INSERT INTO " + table + " (" + keys.join(", ") + ") VALUES (" + ph + ") ON CONFLICT (id) DO UPDATE SET " + upd, keys.map((k) => r[k]));
  return r;
}
export async function update(table, id, cols, record) {
  const keys = cols.filter((c) => c in record && c !== "id");
  if (keys.length) await pool.query("UPDATE " + table + " SET " + keys.map((c, i) => c + "=$" + (i + 2)).join(", ") + " WHERE id=$1", [id, ...keys.map((k) => record[k])]);
  return { id, ...record };
}
export const all = (table) => pool.query("SELECT * FROM " + table).then((r) => r.rows);
export const find = (table, id) => pool.query("SELECT * FROM " + table + " WHERE id=$1", [id]).then((r) => r.rows[0]);
`,
    "src/events.js": `const N8N = process.env.N8N_BASE_URL;
// Emit a domain event: log it, and (if configured) POST to the n8n webhook the generated workflow listens on.
export async function emit(name, payload) {
  console.log("[event] " + name + " " + (payload && payload.id ? payload.id : ""));
  if (N8N) { try { await fetch(N8N + "/on/" + name, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload || {}) }); } catch (e) { console.warn("emit->n8n failed: " + e.message); } }
}
`,
    "src/handlers.js": handlersJs,
    "src/schema.js": schemaJs,
    "src/server.js": `import express from "express";
import { insert, update, all, find } from "./db.js";
import { emit } from "./events.js";
import { handlers } from "./handlers.js";
import { columns, routes } from "./schema.js";

const app = express();
app.use(express.json());
app.get("/health", (_req, res) => res.json({ ok: true }));

// ctx gives handlers read access to the stores without touching SQL.
const ctx = { all: (entity) => all(entity), find: (entity, id) => find(entity, id) };

for (const r of routes) {
  const path = r.path.replace("{id}", ":id");
  app.post(path, async (req, res) => {
    try {
      const input = { ...req.body, ...(req.params.id ? { id: req.params.id } : {}) };
      const handler = handlers[r.command] || ((i) => ({ ...i }));
      let record = (await handler(input, ctx)) || input;
      record = r.create ? await insert(r.table, columns[r.entity], record) : await update(r.table, req.params.id, columns[r.entity], record);
      for (const ev of r.emits) await emit(ev, record);
      res.status(r.create ? 201 : 200).json(record);
    } catch (e) { res.status(422).json({ error: String((e && e.message) || e) }); }
  });
}

const port = process.env.PORT || 3000;
app.listen(port, () => console.log("spine listening on :" + port + " (" + routes.length + " command routes)"));
`,
  };
}
