import { test } from "node:test";
import assert from "node:assert/strict";
import { assembleFullStack } from "../src/fullstack.ts";
import { DEFAULT_BINDING, type Binding } from "../src/index.ts";
import type { CapabilityDoc, DomainDoc } from "@kiln/compiler";

// A minimal but complete model so assembleFullStack exercises the real compose/.env/placement path.
const capabilities = { domain: "Test", capabilities: [{ id: "leads", name: "Leads", purpose: "", outcomes: [] }] } as unknown as CapabilityDoc;
const domain: DomainDoc = {
  aggregates: [{ id: "lead", name: "Lead", owner: "leads", attributes: [{ name: "email", type: "text" }], references: [] }],
  commands: [{ id: "capture_lead", name: "Capture Lead", aggregate: "lead", capability: "leads", emits: ["lead_captured"] }],
  events: [{ id: "lead_captured", name: "Lead Captured", aggregate: "lead", trigger: "command" }],
} as unknown as DomainDoc;

const gen = (binding: Binding, dialect: "postgres" | "sqlite" = "postgres") =>
  assembleFullStack({ capabilities, domain, binding, dialect, modelPath: "model.json", gitInitialized: true }).files;

// The exact all-local docker-compose (pre-SPEC-012 structure) — the load-bearing byte-identity oracle.
// If the placement-aware compose refactor ever drifts a byte for the default case, this fails.
const EXPECTED_LOCAL_COMPOSE = `# Generated by @kiln/codegen — the backends this system binds to.
services:
  postgres:
    image: postgres:16-alpine
    environment: { POSTGRES_USER: app, POSTGRES_PASSWORD: app, POSTGRES_DB: app }
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  n8n:
    image: n8nio/n8n
    environment: { N8N_DIAGNOSTICS_ENABLED: "false" }
    ports: ["5678:5678"]
    volumes: ["n8ndata:/home/node/.n8n"]
  odoo-db:
    image: postgres:16-alpine
    environment: { POSTGRES_USER: odoo, POSTGRES_PASSWORD: odoo, POSTGRES_DB: postgres }
  odoo:
    image: odoo:17
    depends_on: [odoo-db]
    environment: { HOST: odoo-db, USER: odoo, PASSWORD: odoo }
    ports: ["8069:8069"]
    volumes: ["./odoo:/mnt/extra-addons:ro"]
  spine:
    build: ./spine
    depends_on: [postgres]
    environment: { DATABASE_URL: "postgres://app:app@postgres:5432/app", N8N_BASE_URL: "http://n8n:5678/webhook", PORT: "3000" }
    ports: ["3000:3000"]
  ui:
    build: ./ui
    depends_on: [spine]
    ports: ["8080:80"]
volumes: { pgdata: {}, n8ndata: {}, odoodata: {} }
`;

test("byte-identity: the all-local docker-compose matches the captured pre-SPEC-012 baseline", () => {
  assert.equal(gen(DEFAULT_BINDING, "postgres")["docker-compose.yml"], EXPECTED_LOCAL_COMPOSE);
});

test("byte-identity: an empty hosting object changes no placement-sensitive file (compose + .env)", () => {
  // (model.json legitimately records the binding you pass, so it may differ; the compose/.env must NOT.)
  for (const dialect of ["postgres", "sqlite"] as const) {
    const a = gen(DEFAULT_BINDING, dialect);
    const b = gen({ ...DEFAULT_BINDING, hosting: {} }, dialect);
    assert.equal(b["docker-compose.yml"], a["docker-compose.yml"], `${dialect}: compose unchanged`);
    assert.equal(b[".env.example"], a[".env.example"], `${dialect}: .env unchanged`);
    assert.ok(!("PLACEMENT.md" in b), `${dialect}: no PLACEMENT.md when all local`);
  }
});

test("all-local export: expected services present, exactly one uncommented DATABASE_URL, no placement docs", () => {
  const files = gen(DEFAULT_BINDING, "postgres");
  const compose = files["docker-compose.yml"];
  for (const svc of ["  postgres:", "  n8n:", "  odoo:", "  spine:", "  ui:"]) assert.ok(compose.includes(svc), `compose should have ${svc}`);
  // no duplicate/conflicting reach var (REV-020): exactly one uncommented DATABASE_URL line.
  assert.equal((files[".env.example"].match(/^DATABASE_URL=/gm) ?? []).length, 1);
  // placement descriptors are NOT emitted when everything is local (keeps the export byte-identical).
  assert.ok(!("PLACEMENT.md" in files));
  assert.ok(!("deployment.json" in files));
});

test("remote placement e2e: managed pg + fly spine + vercel ui prunes services, repoints env, emits descriptors", () => {
  const binding: Binding = {
    ...DEFAULT_BINDING,
    hosting: { postgres: { mode: "managed", target: "managed" }, node: { mode: "managed", target: "fly" }, shadcn: { mode: "managed", target: "vercel" } },
  };
  const files = gen(binding, "postgres");
  const compose = files["docker-compose.yml"];
  // managed/remote services are pruned; n8n (still local) stays.
  assert.doesNotMatch(compose, /^ {2}postgres:/m);
  assert.doesNotMatch(compose, /^ {2}spine:/m);
  assert.doesNotMatch(compose, /^ {2}ui:/m);
  assert.match(compose, /^ {2}n8n:/m);
  // descriptors emitted.
  assert.ok("PLACEMENT.md" in files, "PLACEMENT.md");
  assert.ok("deployment.json" in files, "deployment.json");
  assert.ok("spine/fly.toml" in files, "spine/fly.toml");
  // no uncommented DATABASE_URL when Postgres is managed (REV-020/REV-030 — never a baked value).
  assert.equal((files[".env.example"].match(/^DATABASE_URL=/gm) ?? []).length, 0);
  // the store is managed → PLACEMENT.md carries the RLS warning (REV-030).
  assert.match(files["PLACEMENT.md"], /USING \(true\)/);
});

test("remote placement never bakes a credential even if one is (mis)authored in hosting.url", () => {
  // a distinctive password token so the assertion can't collide with unrelated boilerplate ("secrets" etc.).
  const PW = "Zq9xUniquePw";
  const binding: Binding = { ...DEFAULT_BINDING, hosting: { postgres: { mode: "managed", target: "managed", url: `postgres://user:${PW}@db/app` } } };
  const files = gen(binding, "postgres");
  // the password must not appear in ANY generated file (validation flags PB5; projection + persistence redact).
  for (const [path, content] of Object.entries(files)) assert.ok(!content.includes(PW), `credential leaked into ${path}`);
});

test("fully-remote compose (no local service left) is still valid, non-empty YAML — no empty services: block", () => {
  // prune everything prunable in a non-odoo model: pg+n8n managed, spine on fly, ui on vercel. odoo isn't in
  // play here, so its block survives — but assert the guard yields a non-empty services body regardless.
  const binding: Binding = {
    ...DEFAULT_BINDING,
    hosting: { postgres: { mode: "managed", target: "managed" }, n8n: { mode: "managed", target: "managed" }, node: { mode: "managed", target: "fly" }, shadcn: { mode: "managed", target: "vercel" } },
  };
  const compose = gen(binding, "postgres")["docker-compose.yml"];
  assert.doesNotMatch(compose, /services:\n\nvolumes/, "must never emit an empty services: mapping");
  assert.match(compose, /services:\n {2}\S/, "services: must be followed by an indented entry");
});
